연락처관리 [STEP 2] Jenna, JoJo
tasty-code/ios-contact-manager pull request #10
Opened 2022-12-27 08:10 UTC by ueunli

안녕하세요 @corykim0829
빠르고 상세하게 달아주신 피드백 덕분에 같이 의논하고 수정하면서 많이 배울 수 있었습니다!
이번 스텝은 기존에 구현해놓은 타입에 기능만 추가하여서 조금 이르게 마무리한 것 같아요..!
이번 주가 벌써 2022년의 마지막 주네요🥲
연말이라 바쁘실 텐데 여유 되실 때 가볍게 확인해주시면 감사하겠습니다!!
　 

## 구현 사항
1. **사용자 메뉴 입력 발신**
   - [x] 사용자 입력 발신
   - [x] 입력값을 옵셔널 바인딩

2. **사용자 메뉴 입력 수신 및 분기처리**
   - [x] 사용자 입력 수신
   - [x] 열거형 `Menu`로 메뉴별 case 설계
   - [x] 수신된 입력별 switch-case 분기처리

3. **안내문구 출력**
   - [x] 안내문구 메시지 정의
   - [x] 안내문구 메시지 출력

　 

## 구현 과정
> ### 파일 목록
> - Profile: 연락처 데이터 타입 정의
> - InputManager: 입력값 검증
> - **OutputManager**: 안내문 출력
> - ContactManageSystem: 입력값을 통한 데이터 인스턴스 생성
> - ValidInputError: 에러 정의

### 반복문의 반복 조건
입력값 받기, 입력값 처리 2가지를 기능별로 분리하였으며, bool타입 조건을 걸어 종료되기 전까지 반복되도록 했습니다. 
- while문 내부에 `pipeInMenu`함수를 배치
- 반복의 조건은 bool타입 프로퍼티 `repetition`

### 메뉴별 분기처리
입력한 메뉴값에 따라 `Menu` 열거형과 switch-case문을 활용하여 분기처리 하였으며, 원시값을 활용하여 switch-case문에서 가독성 및 통일성을 주었습니다.
- String 원시값을 갖는 열거형 `Menu`
- pipeInMenu 함수에서 입력된 문자열과 원시값이 동일한 case에 매칭

### contactList 타입 변경
초기에는 커스텀타입(Profile)으로 된 데이터를 쉽게 찾고자 String타입 key값에 매칭된 딕셔너리 형태로 저장되도록 구현하였습니다. 
남겨주신 코멘트를 보고 contactList의 네이밍을 고민하던 중, 공개된 Step3의 요구조건에 '동명이인도 저장이 될 수 있어야 한다'는 점을 발견하였습니다. 원래 구현 방식으로는 contactList딕셔너리의 key인 name은 중복이 금지되어 있어, 동명이인의 Profile인스턴스를 생성해도 별개로 저장할 수 없었습니다. 
그래서 기존의 딕셔너리를 요소로 갖는 2차원 배열로 타입을 개편할까 알아보던 중, 
커스텀타입인 Profile 인스턴스의 속성에 직접 접근할 수 있다는 사실을 테스트를 통해 알게 되었습니다. 
더불어 기존 네이밍에도 적합하다고 생각되어, Profile타입 인스턴스를 요소로 갖는 배열로 설정해도 괜찮겠다는 결론을 내리게 되었습니다.

### OutputManager 분리 구현
출력 문구가 많아지면서 output을 담당하는 구조체의 필요성을 느끼게 되었습니다. 
하지만, OutputManager를 구현해본 적이 없어 객체 간 상호작용을 어떻게 해야할지 고민이 많았습니다. 
`InputManager → contactManageSystem → outputManager` 형태로 구현해야 할지, 
`InputManager → contactManageSystem ← outputManager` 형태로 구현해야 할지 의논해 보다가 
`contactManageSystem`에서 전체적인 데이터를 처리하는 것이 구조적으로 맞다고 생각되어 후자로 결정했습니다. 
> ❓ **조언이 필요한 부분**
> 현재 outputManager는 문구를 저장하는 private 프로퍼티와 이들 각각을 출력하기 위한 메서드로 구성되어 있습니다. 
> 각 프로퍼티에 대한 메서드를 따로따로 작성하는 것보다 좋은 방법이 있을 듯한데 찾지 못했습니다. 
> 다른 좋은 방법이 있을까요?

---
### 실행 예시 ↓ 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/67406889/209628453-75ec5a50-f74f-42fe-a29c-ab2f61f4f79f.png">

2022-12-27 16:13 UTC, corykim0829 requested changes
두번째 스텝도 수고 많았어요 Jenna, JoJo! 👏👏👏

OutputManager를 잘 추가하셨고, 추가된 후에도 구조는 안정적이여서 보기 좋습니다 👍
고민하신 것 처럼, ContactManagerSystem 안에 하위 객체로 Input, Output 매니저들에게 상위 객체가 일을 시키는 형태로 처리하는게 좋습니다 😀

하지만 ContactManageSystem 구조체 안에 ContactManageSystem 인스턴스가 사용되고 있는 점은 불필요한 코드같아 보입니다!
이 부분을 먼저 개선하면 좋겠네요 😀

두번째 스텝도 하느라 고생많으셨습니다.

다음 미션이나, 스텝에서는 main 브랜치가 아닌 step 브랜치를 만들어서 PR을 날려주세요!

남은 미션 화이팅입니다!!

2022-12-27 16:13 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    static func start() {
static func로 선언한 이유는 무엇인가요?
그냥 func와 어떤 차이점이 있나요?

2022-12-27 16:13 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +        var contactManageSystem = ContactManageSystem()
ContactManageSystem 구조체 안에서 또 ContactManageSystem 구조체 인스턴스를 선언한 이유는 무엇인가요?

2022-12-27 16:13 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    func receiveMenu() throws -> String {
receiveMenu() 함수명만 보면 반환타입이 없는 것 같이 느껴져서 조금 어색한 부분이 있네요!
함수명을 개선해보면 좋을 것 같아요.
저는 함수가 실제 사용되고 있는 부분을 한번 확인하면서 가독성을 고민해보면 더 좋더라고요!

2022-12-27 16:13 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    mutating func pipeInMenu(input: String) {
pipeInMenu 함수는 어떤 의미로 이렇게 네이밍을 한건지 한번 설명해주실 수 있을까요? 😮

2022-12-27 16:13 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +        switch Menu(rawValue: input) {
input으로 Menu enum 인스턴스를 생성할 때, 옵셔널 처리를 하면 조금 더 깔끔한 switch case 문을 작성할 수 있을 것 같아요!
또한 switch에 바로 생성자 형태로 넣기보다는 줄바꿈을 해주면 더 좋을 것 같아요 😃

2022-12-28 09:08 UTC, CODEMASTERJO commented
안녕하세요 @corykim0829 
주신 피드백 jenna와 함께 고민하고 수정해서 다시 push하였습니다~

이전 PR 보낸 후에도 타입 메서드 및 네이밍에 지식이 부족하여 같이 스터디를 진행해보았습니다.
스터디 진행하며 찾아본 자료도 함께 첨부드립니다.

----

### 네이밍

- [x]  contactList 
  - `contactList` → `profileData` (프로필 데이터 담고있는 바구니라고 생각하여 명칭을 변경하였습니다.)
- [x]  repetition 
  - `repetition` → `isFinished` (참고자료 네이버 네이밍 강의에서 Bool타입은 is로 시작하여야 한다는 내용을 참고하였습니다.)
- [x]  receiveMenu 
  - `receiveMenu` → `deliverMenuInputValue` (받는거뿐만 아니라 값을 내보내고 있는 처리도 진행하고 있어 `deliver`라는 단어를 사용하였으며, 뒤에 목적어에 대해 명확히 기입하였습니다.
- [x]  pipeInMenu 
  - 값을 받아서 분기별로 특정 기능을 수행하고 있어서 `pipeInMenu`라는 명칭을 사용했으며, 영문어순을 고려하여 매개변수도 수정하였습니다.

### 구조

- [x]  static func vs func
    - 이전에 타입 메서드에 기능에 대해 이해하고 있었지만 어디에 사용해야 하는지를 명확히 알지 못했습니다. 팀원과 스터디 진행결과 아래와 같은 답을 얻었습니다. 
    - 타입 속성과 메서드는 언제써야할까? → 공유값, 설정값 등 구조체내에서 공통적으로 가지고 있어야 하거나 공유가 필요한 값
    - 해당 함수는 공유 및 설정에 해당되지 않는다고 생각하여 인스턴스 메서드로 변경하였습니다.
- [x]  ContactManageSystem 구조체 인스턴스 생성 이유
    - 인스턴스 메서드를 사용하기 위해 인스턴스를 생성하여 변수에 담아두었습니다. 해당 과정은 타입 메서드를 수정하여 `ContactManager`의 인스턴스 메서드 내에서 처리되도록 변경하였습니다.


### 질문한 부분

- [x]  OutputManager enum으로 변경
    - 주신 조언대로 참고하여 기존 `struct`에서 `enum`으로 변경하였으며, `switch-case`를 활용하여 각 문구별로 분기처리하였습니다. 또한, print를 공유하고 있다고 생각하여 static 메서드를 적용해 봤습니다.
- [x]  enum rawValue 옵셔널
    - 기존에 `default`를 필수 구현하라고 컴파일 경고가 발생하여 의문을 가지고 있었는데, `rawValue`를 통한 열거형의 생성자는 실패가능이므로 옵셔널 타입이라는 것을 알게 되었습니다. 옵셔널 바인딩을 통해 nil 가능성을 제거함으로써 `default`문을 구현하지 않아도 되었습니다.


### 참고자료
[[Swift] static과 class method, property 효과적으로 사용하기](https://sujinnaljin.medium.com/swift-static과-class-method-property-효과적으로-사용하기-b336311a923c)
[영어 변수명을 잘 지어보자](https://www.youtube.com/watch?v=rbSnkiqPnJI)
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)

2022-12-29 04:09 UTC, CODEMASTERJO commented
안녕하세요 @corykim0829 

Discord에 말씀드린 대로 STEP 3 구현사항 함께 추가해서 올립니다!

----

## 구현사항

### 연락처 목록보기 함수

- [x]  contactList 
  - `contactList` → `profileData` (프로필 데이터 담고있는 바구니라고 생각하여 명칭을 변경하였습니다.)
- [x]  repetition 
  - `repetition` → `isFinished` (참고자료 네이버 네이밍 강의에서 Bool타입은 is로 시작하여야 한다는 내용을 참고하였습니다.)
- [x]  receiveMenu 
  - `receiveMenu` → `deliverMenuInputValue` (받는거뿐만 아니라 값을 내보내고 있는 처리도 진행하고 있어 `deliver`라는 단어를 사용하였으며, 뒤에 목적어에 대해 명확히 기입하였습니다.
- [x]  pipeInMenu 
  - 값을 받아서 분기별로 특정 기능을 수행하고 있어서 `pipeInMenu`라는 명칭을 사용했으며, 영문어순을 고려하여 매개변수도 수정하였습니다.
  -

2022-12-29 04:59 UTC, CODEMASTERJO commented
안녕하세요 @corykim0829 

Discord에서 말씀드린대로 STEP3 내용까지 추가했습니다!
바쁘실텐데 양해해주셔서 감사합니다.😭

이제 겨우 하나의 프로젝트를 진행했는데 코드리뷰를 하면서 혼자서는 절대 몰랐을 부분을 많이 알 수 있었고
해당 부분에 대해 추가적으로 학습을 진행하면서 저희껄로 만들 수 있었습니다.
항상 격려해주신 덕분에 의욕적으로 공부할 수 있었어요!!!~~ 🔥

벌써 2022년이 다 지나갔네요. 올해도 내년도 바라는 일, 행복한 일 모두 이루시기 바랍니다~

　
　
　
## 구현사항

### ✅ 연락처 전체목록 조회(Menu 2번)

#### 연락처 목록 조회 기능
- [x] ContactManageSystem - profileData 타입 요구사항에 따라 set으로 전환
- [x] ContactManageSystem - profileData에 sorted함수를 통해 값을 정렬하고, foreach함수를 통해 데이터별 출력문구 생성
####  연락처 목록 출력 기능
- [x] OutputManager - printProfileList, printNoMatchingData 함수를 활용하여 조건에 따른 출력문구 표시

### ✅ 연락처 검색결과 조회(Menu 3번)

- [x]  타겟 입력값 받기
  - InputManager - targerInput을 통해 사용자 입력값 받기
- [x]  타겟 입력값과 저장속성 비교 
  - filter함수를 통해 name저장속성이 입력값과 일치하는 Profile 인스턴스만 필터링
- [x]  조건에 따른 guard문 처리
  - 검색결과가 0개일 경우 -> OutputManager - printNoMatchingData 작동
  - 검색결과가 1개 이상일 경우 -> OutputManager - printProfileList 작동

### ✅  추가사항
#### profileData의 타입
- [x] step2에서 딕셔너리 → 배열로 타입을 변경했었는데, 이번에 프로젝트 핵심경험을 하나씩 체크하던 중 'Set 사용'에 관한 내용을 발견했습니다. 
name이 같아도 age, tel이 다르면 다른 Profile인스턴스로 인식되므로 동명이인 저장 문제도 없으리라 판단하여, profileData의 타입을 Set<Profile>로 변경하였습니다.

2022-12-29 08:44 UTC, corykim0829 requested changes
step3까지 수고가 많으셨습니다 👏👏👏

마지막 스텝까지 정말 고생 많으셨고, 제가 조금 애매하게 피드백을 해드린 부분이 있었거나 헷갈리는 부분이 있다면 언제나 다시 물어봐주셔도 좋습니다 ㅎㅎ

JoJo, Jenna 두분 모두 고생 많으셨어요 😊😊😊 2022년 마무리 잘하시길 바랍니다 🙏

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    var profileData = Set<Profile>()
profileData라고 하면, profile 하나의 데이터를 의미하는 것 가아서, 복수형 profiles을 사용하는게 더 명확하게 의미가 전달될 것 같아요 😊
값의 중복 방지를 위해 Set으로 변경한 점이 좋네요 👍

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    mutating func pipeInMenu(_ input: String) {
해당 함수 구현부 들여쓰기 정리해주세요!

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +            OutputManager.printNoMatchingData(name: targetInput)
guard문을 사용한게 조금 어색하게 느껴져요.
보통 guard는 이름 처럼 막는 조건문이기 때문에 else 바디에서 예외 처리를 해주는데, 지금은 반대의 경우가 되어서 어색한 것 같습니다!

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/OutputManager.swift
> +enum OutputManager: String {
OutputManager가 enum이 되버리면, 조금 어색한 것 같아요.
또한 이 문구 String들은 OutputManager 내부에서만 사용하기 떄문에 Text나, Message와 같은 이름으로 OutputManager의 구조체 혹은 클래스의 nested enum으로 선언하면 좋을 것 같습니다!

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/OutputManager.swift
> +    static func printMessage(_ text: OutputManager) {
자기 자신을 파라미터로 다시 호출하는게 조금 어색한 것 같아요! 👀

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManager.swift
> +struct ContactManager {
ContactManagerSystem의 상위 객체는 사실상 run 함수 하나만 가지고 있어서, 지금 당장은 불필요해보입니다.
더 깔끔하게 정리할 수 있으면 좋을 것 같아요!

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    func deliverMenuInputValue() throws -> String {
반환값이 있는 함수라면 명사형으로 깔끔하게 네이밍하는 것도 좋습니다. 참고하세요! 😊

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    func listUpProfile() {
이 함수와 아래 searchProfile() 함수는 모두 private으로 선언해도 될 것 같네요.
프로퍼티나 함수 모두 객체지향적인 코드를 위해 private을 우선으로 고려하는게 좋습니다! 😊

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +            let filteredProfileData = profileData.filter { $0.name == targetInput }
고차함수를 이용한 search 방식이 재밌네요 👍

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +            let targetInput = try inputManager.targetInput()
inputManager의 함수명이 targetInput인 거는 추상적으로 input을 가져온다는 의미에서 괜찮은데, 가져온 targetInput 상수명도 targetInput이면 조금 추상적이여서 현재 함수 문맥에 맞는 상수명으로 변경하면 좋을 것 같아요!
이름을 나타내면 좋을 것 같습니다 😊

2022-12-29 08:44 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +                OutputManager.printProfileList(filteredProfileData)
파라미터와 함수명이 중복되지 않게 다음과 같이 표기하는게, Swift 네이밍 가이드에 준수하는거에요! 😊
```suggestion
                OutputManager.print(profiles: profiles)

2022-12-30 16:33 UTC, corykim0829 approved these changes
수고 많으셨습니다!!

스텝1 부터 do catch문을 사용하여 에러 핸들링을 잘 하신 것 같습니다! 👍
첫번째 미션 정말 고생 많으셨고 다음 미션도 화이팅입니다!!!
새해 복 많이 받으세요 🧧

2022-12-30 16:33 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManager.swift
> +//struct ContactManager {
주석 처리한 부분은 파일을 아예 제거하면 좋을 것 같습니다!

2022-12-30 16:33 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    var isFinished = false
프로퍼티는 우선적으로 private으로 구현하는게 좋습니다! 은닉화를 찾아보시면 좋을 것 같습니다 :)

2022-12-30 16:33 UTC, merged