연락처관리 [STEP 2] Miro, Lust3r
tasty-code/ios-contact-manager pull request #12
Opened 2022-12-28 08:46 UTC by llimental

🙇🏼‍♂️ 인사말
========
안녕하세요 라자냐(@wonhee009)! Miro와 Lust3r 입니다.
STEP 2 요구 사항에 맞추어 코드를 작성하고 커밋을 해보았습니다.

감사합니다

✅ 요구사항 & 체크리스트
========
- [x] 사용자에게 동작을 선택할 메뉴를 표기합니다.
- [x] 1, 2, 3, x 외의 입력을 받으면 잘못된 입력을 알리고 다시 메뉴를 출력합니다.
- [x] 연락처 추가와 종료 기능만 우선 구현합니다.
- [x] 연락처 목록보기와 연락처 검색 기능은 다음 스텝에서 구현합니다.

📝 Summary
========
> 메뉴 반복을 위해 while을 사용하고, 사용자 입력값 분기를 위해 switch..case 처리를 하였습니다.
추가로 main파일에 많은 function이 생기게 되어 가독성을 높이고자 별도의 파일로 분리 해보았습니다!

🔎 구현 방법
========
## 메뉴 출력
```swift
var isMenuInputError: Bool = false
let regex = "^[A-Za-z\\s]+$"

while !isMenuInputError {
    print("1) 연락처 추가 2) 연락처 목록보기 3) 연락처 검색 x) 종료")
    print("메뉴를 선택해주세요 : ",terminator: "")
    guard let input = readLine(), input != "" else{
        continue
    }
    switch input{
    case "1":
        addContact()
    case "2":
        continue
    case "3":
        continue
    case "x":
        isMenuInputError = true
    default:
        print("선택이 잘못되었습니다. 확인 후 다시 입력해주세요.\n")
        continue
    }
}
```
- isError 변수로 하였으나 addFunction에서 같은 구성을 취하면서 통일성을 이루고자 규칙을 만들었습니다.(어디서의 오류인지)
-  전체를 while문으로 감싸 'x' 입력값이 들어오기 전까지는 isMenuInputError 값이 false로 유지되게하여 계속해서 반복문을 돌 수 있게 하였습니다. 
> 만약 '1'로 input값이 들어오게 된다면, STEP[1]에서 구현한 addContact()가 실행되게 하였습니다.

## addFunction 분리
```swift
func addContact(){
```
- switch..case 문에서 각 기능이 차지하는 공간이 많아 분리하는 것이 좋다고 판단하였습니다.

## 기타사항
- func도 많은 기능을 분리하여 실행하다보니 main 안에서 너무 많은 자리를 차지하여 코드를 한 눈에 보기 어려웠습니다.
때문에 이를 개선하고자 함수를 담을 다른 파일(CheckErrorFunction, Function)을 만들어 이동하게 되었습니다.

🖥️ 실행결과
========
![image](https://user-images.githubusercontent.com/45708630/209784068-9a479ca9-e305-4550-8bda-c2579c08a602.png)

🤔 궁금한 점
========
### 1. 네이밍을 고민하다가 addFunction 파일은 그 함수의 이름을 따 AddContactFunction으로 하였고, 오류 체크 함수는 별도로 CheckErrorFunction, 나머지 함수는 Function 파일로 네이밍을 하였습니다.
1-1. 함수들만 따로 빼서 만드는게 괜찮은 방향인지
1-2. function과 CheckErrorFunction 두 파일로 나눌 때 비슷한 기능을 하는 함수와 이외의 함수로 구분을 지었는데, 이렇게 분류를 하는 게 맞는지
1-3. 3자가 봤을 때 네이밍에 혼동이 오지 않을지
세 가지 질문에 대해 여쭤보고자 합니다.

2022-12-29 15:34 UTC, wonhee009 requested changes
수고하셨습니다~
코멘트 남겨두었으니 확인 부탁드려요.

- 방식에 정답은 없습니다만 저는 항상 이 코드가 잘 읽힐까? 역할 분리가 잘 되었나? 생각을 많이 하는거 같습니다. 이런 관점에서 현재 코드를 보면 `AddContactFunction`같은 네이밍은 의미를 알 수 있는데 `Function`파일은 이름만 보고 어떤 역할을 하는지 잘 모를거 같습니다. 또한, 이렇게 메서드만 파일로 분리하는 경우가 좀 드물기도 하고요. `struct Validation` 같은 구조체를 만들고 검증 관려한 메서드를 안에 정의하고 쓴다던지... 이런식으로 역할을 분리하기도 합니다.
- "swift 메모리 구조" 라는 키워드로 검색해보면 해당 부분에 대해 이해할 수 있을거 같습니다. 첨부해주신 코드를 보면 메서드 내에서 호출되고 있는 변수로 stack에 메모리가 올라갔다가 메서드 호출이 완료되면 해제될거로 보입니다. 따라서, 동일한 이름으로 반복적으로 생성해도 문제 없습니다.
- 아래와 같이 init을 정의해 주고 필요한 프로퍼티들을 init시에 주입해주는 방식으로 풀 수 있을거 같습니다.
``` swift
struct Contact {
   private let name: String
   ...
   
   init(name: String, ...) {
      self.name = name
      ...
   }
}
```

2022-12-29 15:34 UTC, wonhee009 commented on contactManager/contactManager/main.swift
>      }
`AddContact`에서도 해당 조건이 반복되는거 같은데요.
모든 로직(추가/삭제/검색 등...)이 해당 조건을 거쳐서 Input을 받는거 같습니다.
이런 조건은 main에서만 확인하고 추가/삭제와 같은 로직에는 입력받은 Input만 넘겨주도록 하는 방향은 어떤가요?
코드가 반복되기도 하고, 동일 조건을 이중으로 체크하는거 같아서요.

2022-12-29 15:34 UTC, wonhee009 commented on contactManager/contactManager/Function.swift
> +}
`calculate`라는 네이밍만 보면 반환 타입이 `Int`로 예상 가는데요.
여기서는 `Bool` 타입을 반환하고 있어 헷갈릴 여지가 있는거 같습니다. 좀 더 명확한 이름은 어떨까요?

2022-12-29 15:34 UTC, wonhee009 commented on contactManager/contactManager/FindContactFuction.swift
> +        print("- \(contact.name) / \(contact.age) / \(contact.phoneNumber)")
검색, 목록보기에서 동일하게 사용되는 출력문으로 보이는데요.
``` swift
struct Contact {
   let name: String
   ...
  
   var description: String {
      "- \(self.name) / \(self.age) / \(self.phoneNumber)"
   }
}


print(contact.description)
```
이런식으로 `Contact` 안에 정의해두고 꺼내 쓸 수 있을거 같습니다.

2022-12-29 15:34 UTC, wonhee009 commented on contactManager/contactManager/FindContactFuction.swift
> +    }
``` swift
for contact in ContactSet {
   guard contact.name == inputName else { continue }
   print("- \(contact.name) / \(contact.age) / \(contact.phoneNumber)\n")
   return
}
print("연락처에 \(inputName) 이(가) 없습니다.\n")
```
이런식이면 correctCount가 없어도되지 않나요?

2022-12-30 01:06 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
> +var ContactSet : Set<Contact> = []
타입을 통해서 이미 Set이라는 걸 알 수 있기에 연락처 모음이라는 뜻으로 contacts로 프로퍼티 명을 변경하겠습니다. 감사합니다.🙇‍♂️

2022-12-30 01:16 UTC, llimental commented on contactManager/contactManager/main.swift
> +        }
for문 안에서만 사용되는 것이기에 단순히 지었던 것 같습니다. 네이밍 다시 해보도록 하겠습니다!

2022-12-30 01:29 UTC, longlivedrgn commented on contactManager/contactManager/FindContactFuction.swift
> +    }
@wonhee009 앗 저희도 처음에는 그렇게 코드를 짜보았는데, 이럴 경우에는 같은 이름의 연락처 정보가 들어올 경우, 하나의 연락처만 출력이되어서 correctCount를 통해서 출력을 하게되었습니다!

2022-12-30 02:14 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
> +    print("메뉴를 선택해주세요 : ",terminator: "")
넵! 공통되는 print문은 enum 타입으로 설정하여 출력하도록 변경해보겠습니다. 감사합니다!🙇‍♂️

2022-12-30 04:06 UTC, llimental commented on contactManager/contactManager/main.swift
> +    case "1":
가이드와 같이 수정한 결과 case별 값을 한 눈에 보기 좋아졌고, switch문에서도 guard let을 거쳐 들어오기 때문에 default 를 제외하고도 진행되는 점 확인했습니다!

2022-12-30 04:26 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
>      }
@wonhee009 명세서를 참고하여 메뉴 선택시 input 되는 값과 메뉴 선택 후 연락처 정보를 input하는 값을 별도로 받을 수 있게 코드를 짜보았습니다! 조건이 반복된다는 말씀이 정확히 어떤 부분을 말씀하시는 지 여쭤봐도 괜찮을까요?

2022-12-30 04:29 UTC, longlivedrgn commented on contactManager/contactManager/Function.swift
> +}
`Bool` 타입을 return하는 점을 고려하여 `validateInputByHyphenNum`로 함수 명을 변경하였습니다! 감사합니다🙇‍♂️

2022-12-30 05:06 UTC, wonhee009 commented on contactManager/contactManager/main.swift
>      }
``` swift
guard let input = readLine(), input != "" else { continue }
```
이 부분 말씀드린거였습니다! 코멘트 범위가 더 크게 잡혔네요...!

2022-12-30 05:24 UTC, llimental commented on contactManager/contactManager/FindContactFuction.swift
> +        print("- \(contact.name) / \(contact.age) / \(contact.phoneNumber)")
해당 항목의 이해를 위해 여러모로 찾아본 결과 연산 프로퍼티라는 것을 알게 되었고 활용할 수 있었습니다! 감사합니다

2022-12-30 06:34 UTC, longlivedrgn commented
안녕하세요 라자냐(@wonhee009)
바쁜 와중에도 저희 코드 검토해주셔서 감사합니다. 코멘트 달아주신 부분 확인하여 아래와 같이 수정을 해보았습니다. 감사합니다!🙇‍♂️

변경사항
=====
### 1. Function의 내용은 struct Validation같은 구조체를 만들고 검증 관련한 메서드를 안에 정의
- 아래와 같이 Validation struct을 정의하고 타입 메소드를 생성하여 검증과 관련된 메서드를 외부에서 사용할 수 있게 해보았습니다.
```swift
struct Validation {
    static func validateInputBySlash(input: String) -> Bool {
        guard (input.filter{ $0 == "/" }.count == 2) else {
            return false
        }
        return true
    }

    static func validateInputByHyphenNum(input: String) -> Bool {
        guard (input.filter { $0 == "-" }.count == 2) else {
            return false
        }
        return true
    }
}
```
### 2. `ContactSet` 프로퍼티명 변경
- 기존의 `ContactSet` 변수명을 `contacts`로 변경하였습니다.


### 3. `GuideText` enum을 통하여 반복되는 출력문 정의
- 아래의 코드와 같이 단계마다 반복되는 출력문을 enum으로 묶어줬습니다.
```swift
enum GuideText {
   static let menu = "1) 연락처 추가 2) 연락처 목록보기 3) 연락처 검색 x) 종료"
   static let selectMenu = "메뉴를 선택해주세요 : "
}
```


### 4. ErrorType enum 과 errorTextOutput 함수를 통한 에러 text 출력
- 아래와 같은 코드를 통하여 ErrorType을 enum으로 케이스 분류하고, 함수 호출을 통하여 각 case 별로 해당 에러 text를 출력하도록 구현하였습니다.
```swift
enum ErrorType{
    case name
    case age
    case phoneNumber
}

func errorTextOutput(with type: ErrorType){
    let errorText: String
    switch type {
    case .name: errorText = "이름"
    case .age: errorText = "나이"
    case .phoneNumber: errorText = "연락처"
    }
    print("입력한 \(errorText)정보가 잘못되었습니다. 입력 형식을 확인해주세요.")
}
``` 


### 5. `num` 변수를 `contact`로 변경
-  기존 for 문의변수 `num`을 `contact`로 변경하여 의미를 명확하게 하였습니다.
```swift
    for contact in contacts {
        guard contact.name == inputName else {
            continue
        }
        correctCount += 1
        print(contact.description)
    }
```

### 5. `calculateHyphenNum` 네이밍을 `validateInputByHyphenNum`으로 변경
- 함수명 변경을 통하여 의미를 더 명확하게 하였습니다.


### 6. struct안에 description 변수 생성
- description 연산 프로퍼티를 통하여 같은 형식의 출력이 필요한 곳에서 사용할 수 있도록 구현하였습니다.
```swift
struct Contact : Hashable {
    let name : String
    let age : String
    let phoneNumber : String
    
    var description: String {
          "- \(self.name) / \(self.age) / \(self.phoneNumber)"
       }
}
```


궁금한 점 🤔
=======
코멘트 해주셨던 부분 중, AddContact 함수에서  조건이 반복이 된다는 코멘트에대해서 여쭤보고싶은 게 있습니다.
저희는 아래와 같은 순서를 통하여 연락처 추가 검증 로직을 구현하였습니다.

1. 아래의 코드를 통하여 메뉴 선택에서 잘못 들어온 input 값을 검증합니다.
```swift
 guard let input = readLine(), let menu = MenuType(rawValue: input) else{
        print("선택이 잘못되었습니다. 확인 후 다시 입력해주세요.\n")
        continue
    }
``` 
2. 검증 후, 만약 위의 코드를 통하여 들어온 input 값이 "1"이라면 switch문을 거쳐 addContact()함수를 호출하게 됩니다.
3. addContact() 안에서 다시한번 readline()을 통하여 연락처 정보를 받고, 아무것도 입력되지 않았을 경우 에러 메세지를 출력하고 반복적으로 readline()함수를 호출하여 입력값을 검증합니다.
```swift
    while !isAddContactError {
        print("")
        print("연락처 정보를 입력해주세요: ", terminator: "")
        
        guard let input = readLine(), input != "" else {
            print("아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요.")
            continue
        }
```

- 저희는 위와 같은 로직을 통하여 기능을 구현하였는데, 각 케이스별로 다른 입력값을 받아야 하기에 해당 코드를 몇 번 사용하게 되었습니다. 앞선 comment에서 말씀하신 내용이 아래의 두 코드가 중복되어서 조건을 체크한다고 말씀해주신건지 저희가 아직 이해가 부족하여 혼동이 오는 것 같습니다. 저희가 어느 부분에서 혼동을 하고 있는 지 말씀해주시면 감사드리겠습니다!🙇‍♂️
```swift
    guard let input = readLine(), let menu = MenuType(rawValue: input) else{
        print("선택이 잘못되었습니다. 확인 후 다시 입력해주세요.\n")
        continue
    }
```
```swift
        guard let input = readLine(), input != "" else {
            print("아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요.")
            continue
        }
```

### 라자냐께서 꼼꼼하게 코멘트를 달아주셔서 프로젝트 기간동안 정말 많은 부분을 배울 수 있었습니다. 알려주신 내용 꼼꼼하게 다시 공부하고 복습하여 저의 것으로 만들도록 하겠습니다! 정말 감사합니다!🙇

2022-12-30 06:37 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
>      }
@wonhee009 아 넵!, 저희가 아직 혼동하고 있는 부분이 있는 것 같아 2차 PR을 통하여 달아주신 comment에 대한 내용을 적어보았습니다. 감사합니다!

2022-12-30 09:56 UTC, wonhee009 approved these changes
수고하셨습니다 :)
질문 주신 부분은 아래에 코멘트 남겼으니 확인 부탁드립니다.
이번 과정은 여기서 마무리하도록 하겠습니다~

- 아핫 `guard let input = readLine()`이 동일하게 반복되고 있어서 말씀드렸는데요. (뒤의 조건 menu나 input != ""은 제가 혼동한 부분이 있는거 같네요..!) 이 부분은 제가 착각한게 있어서 클로즈 하겠습니다!

2022-12-30 09:57 UTC, merged