연락처관리 [STEP 2] Avery, Logan
tasty-code/ios-contact-manager pull request #16
Opened 2022-12-29 08:06 UTC by devxsby

## 안녕하세요 Team AL 입니다.🥕🙌🏻

> 안녕하세요 콘 (@protocorn93)!! Avery와 Logan 이에요.
STEP 2 요구 사항에 맞추어 코드를 작성하고 커밋을 해보았어요.
그 전에 STEP 1 구현한 것들을 객체로 조금 쪼개는 과정을 하느라 PR이 늦어진 점 죄송합니다 😿
ERD 설계를 하려고 했는데 다 못해서 일단 순서도를 첨부합니다..!! 다음 STEP3 PR에는 첨부하도록 할게요.
저번 코드리뷰로 많은 걸 배웠어요 이번 리뷰도 잘 부탁드려요 !!! 🙌🏻

## Step 2 요구사항 🌱

- 사용자에게 동작을 선택할 메뉴를 표기합니다.
- 1, 2, 3, x 외의 입력을 받으면 잘못된 입력을 알리고 다시 메뉴를 출력합니다.
- 연락처 추가와 종료 기능만 우선 구현합니다.
- 연락처 목록보기와 연락처 검색 기능은 다음 스텝에서 구현합니다.

<br>

## 구현 사항 및 의도 🧑🏻‍💻

`Step 2 순서도`

![MyContactManager-Step2](https://user-images.githubusercontent.com/80062632/209916949-edce1ffc-8637-419d-a5b1-27141808f05b.png)

`폴더링`

<img width="304" alt="스크린샷 2022-12-29 16 32 36" src="https://user-images.githubusercontent.com/80062632/209918428-c852b70a-02fa-41e7-99df-e275131b8b4a.png">

<br>

## 질문 🤔

### Logan 

어떤 값이 한번 옵셔널이기 시작하면 언젠가 임의값으로 옵셔널을 풀기위한 대체값을 마련하거나 !로 강제 추출하기 전까진 계속해서 옵셔널이란걸 크게 깨달았습니다. (그게 아니라면 결국 nil 로 나오게 되니까요) 이때 현업에서는 어떤식으로 처리하고 계시는지 궁금합니다.
배운바에 의하면 !는 웬만해선(절대로) 쓰지 말라고 했고, 임의값을 넣기에는 앞으로 어떤 상황이 올지 모르기 때문에 마음대로 임의값을 정해서는 안된다고 생각했습니다.

### Avery

Step1 코드를 [리팩토링](https://github.com/tasty-code/ios-contact-manager/commit/3fa4b307355b27f73617857232476272d4291411) 하다 보니, 객체를 쪼개다 보면 끝이 없더라구요... 객체로 쪼개는 것이 아직 어려운데 저희 프로젝트에서는 얼마나 적절한 역할과 책임을 가지고 쪼개면 좋을지 궁금해요. 지금 정도가 적당히 쪼개져 있는지, 아니면 더 얼마나 세분화시켜서 하면 좋을지 궁금해요..!

<br>

## 실행 예시 💻

1. 잘못된 메뉴 입력 시
<img width="421" alt="스크린샷 2022-12-29 16 21 59" src="https://user-images.githubusercontent.com/80062632/209917473-22add160-2264-40f1-8385-ef6584775704.png">

4. 연락처 추가 실패

`입력 값이 없을 시`

<img width="412" alt="스크린샷 2022-12-29 16 27 04" src="https://user-images.githubusercontent.com/80062632/209917930-3985eb95-f242-4559-87ec-e24261d555fd.png">

`나이 입력이 잘못되었을 시`

<img width="474" alt="스크린샷 2022-12-29 16 26 26" src="https://user-images.githubusercontent.com/80062632/209917880-adc35777-26f5-439e-81f3-916ad9fe487f.png">

`연락처 입력이 잘못되었을 시`

<img width="440" alt="스크린샷 2022-12-29 16 27 47" src="https://user-images.githubusercontent.com/80062632/209917994-e6b9b8a2-d4fa-4a64-bbcd-c518affac735.png">

5. 연락처 추가 성공 및 결과 출력

<img width="442" alt="스크린샷 2022-12-29 16 28 05" src="https://user-images.githubusercontent.com/80062632/209918015-a41aa94c-5b3a-426c-8a13-fa9da48b66a0.png">

6. 프로그램 종료

<img width="467" alt="스크린샷 2022-12-29 16 23 07" src="https://user-images.githubusercontent.com/80062632/209917593-a6530689-4414-43e1-9f8f-256e69d27181.png">

2022-12-29 13:13 UTC, protocorn93 requested changes
두 분 모두 수고하셨어요! 일단 간단하게 코멘트 남겨놓았어요! 스탭3를 수행해주고 있는 상황이기 때문에 스탭3에서 좀 더 세세하게 살펴볼게요! 

## 질문 🤔

> Logan
> 
> 어떤 값이 한번 옵셔널이기 시작하면 언젠가 임의값으로 옵셔널을 풀기위한 대체값을 마련하거나 !로 강제 추> 출하기 전까진 계속해서 옵셔널이란걸 크게 깨달았습니다. (그게 아니라면 결국 nil 로 나오게 되니까요) 이때 > 현업에서는 어떤식으로 처리하고 계시는지 궁금합니다.
> 배운바에 의하면 !는 웬만해선(절대로) 쓰지 말라고 했고, 임의값을 넣기에는 앞으로 어떤 상황이 올지 모르기 > 때문에 마음대로 임의값을 정해서는 안된다고 생각했습니다.

이건 정말 케이스가 다양해요! 그럼에도 강제언랩핑은 거의 거의 사용하지 않아요. 사용한다면 개발 과정 중 빠른 crash로 객체가 비어서는 안되는 상황을 알기 위해서 정도일 것 같아요. `??` 을 통해 default 값을 사용하기도 해요. 물론 기능에 따른 앞뒤 논리가 맞아야겠죠! 대부분 `guard-let`,` if-let`을 통해 안전하게 언랩핑을 해서 사용해요! 물론 이 함수에서 벗겨야 하냐, 아니면 외부에서 벗겨서 이 함수에 넣어주어야 하냐는 문제가 있을 수 있어요. 저는 이럴 땐 메서드가 특정 연산을 하거나 기능을 수행하는데 있어 반드시 값이 있어야 하는 상황이면 외부에서 벗겨서 넣어주곤 해요. nil을 반환하거나 처리를 하는 과정이 생기게 되면 결국 메서드 안에서 문맥이 하나 더 생기는 것이기에 그만큼 직관성은 조금 떨어지겠죠!(굉장히 주관적일 수 있는데, 이건 코드를 많이 작성하면서 본인만의 기준을 세우는 것이 중요해요!)

> Avery
>
> Step1 코드를 [리팩토링](https://github.com/tasty-code/ios-contact-> manager/commit/3fa4b307355b27f73617857232476272d4291411) 하다 보니, 객체를 쪼개다 보면 끝이 없더라구요... 객체로 쪼개는 것이 아직 어려운데 저희 프로젝트에서는 얼마나 적절한 역할과 책임을 가지고 쪼개면 좋을지 궁금해요. 지금 정도가 적당히 쪼개져 있는지, 아니면 더 얼마나 세분화시켜서 하면 좋을지 궁금해요..! 

맞아요! 객체로 나누다보면 끝이 없죠! 그럼에도 제가 속한 팀에선 최대한 객체를 많이 나누려해요. 이 과정에서 트레이드오프를 하게되요. 이렇게 나누는 것이 역할별로 나누어서 좋지만, 가독성이 떨어지는가? 다른 동료가 보았을 때 코드 스위칭이 너무 빈번해서 퍼포먼스가 떨어지는가? 유지보수에는 어떤게 더 좋을까? 다양한 케이스를 고려해서 선택하곤해요. 사실 이것 역시 코드를 많이 작성하시면서 자신만의 기준을 세워가시는 것이 중요해요.

2022-12-29 13:13 UTC, protocorn93 commented on MyContactManager/MyContactManager/Module/InputEditor.swift
> +    let outputEditor = OutputEditor()
살짝 욕심을 부리자면 이렇게 의존하는 객체들은 생성자를 통해 외부에서 주입해주면 좋을 것 같아요.

2022-12-29 13:13 UTC, protocorn93 commented on MyContactManager/MyContactManager/Module/Validator.swift
> +struct Validator {
`ProgramManager`는 `class`로 나머지 객체들은 `struct`로 정의한 이유가 궁금해요!

2022-12-29 13:13 UTC, protocorn93 commented on MyContactManager/MyContactManager/Module/Validator.swift
> +struct Validator {
마찬가지로 접근제어자를 한번 다시 살펴보면 좋을 것 같아요

2022-12-30 00:47 UTC, devxsby commented on MyContactManager/MyContactManager/Enum/Messages.swift
> +    case menu = "1) 연락처 추가 2) 연락처 목록보기 3) 연락처 검색 x) 종료\n메뉴를 선택해주세요 :"
말씀해주신 방법이 맞는 것 같다고 생각이 들어서 [b16dd37](https://github.com/tasty-code/ios-contact-manager/pull/16/commits/b16dd371cb726ebe7f269c27848c35dd6c1296aa) 커밋으로 수정해보았어요 !

2022-12-30 00:50 UTC, devxsby commented on MyContactManager/MyContactManager/Model/UserInputModel.swift
> +    }
- 현재 `UserInputModel`에서 아예 다른 값을 만들긴 하지만 `UserInputModel`의 값을 활용하기 때문에 `convertToPerson `를 이곳에서 만들어서 `Person` 객체를 반환하는 것을 외부에서 모르게 하려고 은닉화하려고 했어요..! 생각해보면 모델 안에서는 어떤 메서드가 있어야 적당할까라는 생각이 듭니다..!! 🤔 밖에 있어도 상관이 없는 코드이긴 합니다!!

- 코드 줄 수를 줄이려고 했는데 좋지 않은 방법인 것 같아 콘이 말씀해주신 방법으로 [수정](https://github.com/tasty-code/ios-contact-manager/pull/16/commits/30c42c8d18a38ddca5aa7ecbada2180f036d39cf)해보았어요. 감사해요 👍🏻

2022-12-30 00:52 UTC, devxsby commented on MyContactManager/MyContactManager/Module/Validator.swift
> +struct Validator {
`ProgramManager`를 처음 만들때 별다른 의미없이 클래스로 만들었는데 상속 할게 아니라면  struct로 바꿔도 될 것 같다는 생각이 들어요..! 말씀해주신 접근제어자도 다시 살펴보도록 할게요 😃

2022-12-30 02:42 UTC, merged