ContactManager [STEP 1] Jason, Blue
tasty-code/ios-contact-manager pull request #2
Opened 2022-12-23 06:44 UTC by JasonLee0223

안녕하세요 소대! Jason & Blue입니다! 🙋🏻
이번 주는 수업 시간이 많아 Step1을 다 마무리 못했네요..ㅠㅠ 그래도 열심히 작성해보았습니다!!
모든 커밋과 작업에 대해서는 모르는 부분 또는 이해가 안가는 부분은 서로 설명하면서 진행하였습니다.
최대한 학습에서 배웠던 타입화를 만들기위해 모델링 작업을 해보았으며 protocol도 사용해보았습니다! 🤭
코드가 출력까지는 동작을 하는데 확인을 하였지만 정상적으로 동작하지는 못하고있습니다..
양해부탁드리며 리뷰 잘 부탁드립니다! 감사합니다! 🙇🏻🙇🏻🙇🏻

## 🧑🏼‍💻 작업 목록
[ STEP 1 ]
- [x]  사용자 입력을 받는 동작을 구현한다.
- [x]  출력 내용과 입력방법은 예시와 똑같이 따른다.
- [x]  입력받은 문자열을 검증한다.
    - [ ]  올바른 사용자 입력 형태: [이름] / [나이] / [연락처]
    - [ ]  예시: James / 30 / 05-111-1111
- [ ]  입력받은 내용을 검증하여 사용자에게 안내문을 출력한다.

### 💡상세 요구사항 분석
- [X] [나이] 항목에서 한글지원 X -> 숫자만 지원
- [X] [번호] 항목에서 구분선(-) 있어야한다.
   - [X]  앞에 지역번호 2~3글자만
    - [X]  중간번호 3~4글자만
    - [X]  마지막은 무조건 4글자만
- [X]  [나이] 항목에 숫자+한글 X, 하이픈(-) 없이 공백처리 인정X
- [X]  [이름] 항목에서 첫번째 띄어쓰기 없이 작성
- [X]  [나이], [번호] 항목이 서로 바뀌어서 입력은 인정X

## 💭 학습 키워드
- 정규표현식(RegularExpression)
- guard-let (Early Exit)
- Optional
- property & Instance
- String & Character

## 🤔 고민과 해결
### Jason
1. 입력 조건을 어떻게 해결해야할까??
입력 조건으로 `_/_` 와 '/' 키워드만 넘어갈 수 있게 해야했습니다.   
키워드가 중간에 있음으로 키워드만 추출하여 입력값을 원하는 값으로 받아내보려고했습니다.
- readLine에서 `split`, `component`를 사용해보려고 했습니다. -> ❌
- `_/_` 와 '/' 입력을 각각 받아보려고 했습니다. -> ❌ 
   사용자의 입력은 한 번인데 2번 받는 부분이 맞지 않았습니다.
- 입력 받은 값은 String 문장을 joined() 메서드를 사용해보려고 했습니다. -> ❌
   joined() 메서드는 배열에서만 가능하단걸 뒤늦게 알았습니다...
   하여, prefix, suffix를 시도하였는데 접두어와 접미어만 추출한다는 것을 알게되었습니다.
-  입력값 String을 Character 배열로 변환하여 `/`만 남기고 `'_'`는 걸러낼 수 있도록 하였습니다. -> ⭕️

2. 짝프로그래밍을 진행하면서 의사소통에 어려움이 있을 것 같아 Blue의 도움을 받아 `수도코드` 에 대해 알게되었습니다.   
   하여 수도코드를 작성하여 모델을 만들어 진행하고 커밋 단위를 네비게이터 역할을 맡았을 때 작성하게되었습니다.   
   모두 동일하게 구현하지는 못했지만 되도록 많이 말을 맞춰가며 해보았습니다.   
   수업중에 추천받았던 순서도를 Blue가 피그마를 잘 사용하여 한 번 시도해보았습니다!
   ```Swift
   // 연락처정보 구조체를 따르는 변수
    let 전화번호부: [연락처정보]

    // 사용자의 입력
    // readLine()으로 받아온 값은 옵셔널 String 타입이므로
    // 사용하기 전에 언래핑해야 함
    // if 대신 guard를 사용하는 이유: 사용자 입력값을 계속 사용해야 하기 때문
    guard let 사용자입력: String? = readLine() else {
        return 에러처리
    }

    // 이름, 나이, 연락처를 갖는 타입 구현 `연락처 정보를 구조체로 사용하기 위해서!`
    struct 연락처정보 {
        let 이름: String
        let 나이: String
        let 연락처: String
    }
   ```
   
   <img src = "https://user-images.githubusercontent.com/92699723/209285066-91da0993-ecb5-4675-9473-1754c2cf262b.png" width="300">

### Blue
- main.swift 에서
    ```swift
    extension ContactManager {
        func joinWords(first index1: Int, second index2: Int, this word: [Character]) -> [Character] {
            var usefulValue = [Character]()
            for index in index1..<index2 {
                usefulValue.append(word[index])
                if word[index] != "/" {
                    break
                }
            }
            return usefulValue
        }
    }
    ```
    
    - ‘/’(이하 구분자)가 위치한 index들을 가지고 있는 배열을 `slashIndexArray` 범위로 활용하여 문자 배열에서 가치있는 문자열로 만들기 위해 배열에서 추출하는 과정을 수행하는 joinWords 메서드를 설계하다가 어려움을 겪었습니다.   
    우선 생각해 둔 문제 해결 과정은 아래와 같습니다.
        - 예시 입력) aaa / bbb / ccc
        - 위의 예시 입력에서 공백을 제거하고 난 후 구분자의 위치 인덱스는 3, 7입니다.
            - aaa를 추출하기 위해 → index1: 0, index2: 2
            - bbb를 추출하기 위해 → index1: 4, index2: 7
            - ccc를 추출하기 위해  → index1: 8, index2: 10
        - index1, 2를 slashIndexArray 배열을 활용하여 해결하고 싶은데 aaa의 경우 0값을 할당하면 되지만   
        bbb와 ccc의 경우 배열에 있는 Int를 가져다 사용하는 경우 해당 위치 인덱스에서 +1씩 더해야 합니다.
        - joinWord 내에서 index1에 1을 더한다고 전제한다면, aaa 추출을 위해 joinWords 사용 시 Index1에 -1을 할당하면 될 것 같은데, 그렇게 된다면 코드가 보기 좋지 않을 것 같아서 고민이 됩니다.   
        이름, 나이 연락처를 따로따로 추출하도록 메서드를 분리하는 게 좋을까요? 다른 좋은 개선방향이 있으면 말씀 부탁드립니다!

## 🙋🏻 질문 거리
### Blue
- 전체적인 네이밍 상태가 궁금합니다.
    - 좋은 네이밍, 좋지 않은 네이밍과 개선점이 있으면 말씀 부탁드립니다!

2022-12-26 11:29 UTC, zdodev requested changes
안녕하세요. @JasonLee0223 , @bomyuniverse !
리뷰를 진행하게 된 소대입니다!😁

첫 프로젝트, 첫 PR 축하합니다!

코드에서 문제를 해결하기 위해 고민한 흔적이 많이 보입니다!
한 곳에서 코드를 작성하지 않고 타입을 나눠서 구현하신 점이 좋았습니다!👍

몇 가지 궁금한 사항을 남겨보았습니다.
피드백은 꼭 수정해야 하는 것이 아니라 생각, 의도에 대한 코멘트를 남겨주셔도 좋습니다!🤗

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +class ContactManager {
main.swift 파일에서 `ContactManager` 타입을 정의해주셨네요! 다른 타입과 다르게 해당 파일에서 정의하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +    func processStart() {
동작 또는 행위를 나타내는 단어를 메서드 이름 앞에 작성하는 것은 어떨까요?
네이밍의 절대는 없지만 관례적으로 많이 사용하는 네이밍 규칙을 적용해보면 좋을 것 같습니다!
[Swift API Design Guide](https://www.swift.org/documentation/api-design-guidelines/#naming) 문서를 참고해보면 좋겠습니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +        var identifier = ""
xcode 에서 warning 이 발생하고 있습니다. 해결해 볼 수 있을까요?

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +            let phoneNumberString = checker.checkCorrectWord(target: convertor.convertToString(phoneNumberWord))
xcode 에서 warning 이 발생하고 있습니다. 해결해 볼 수 있을까요?

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +extension ContactManager: InputPossible {
`extension` 을 사용하여 `InputPossible` 프로토콜을 채택하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +            return "F"
사용자 입력이 없을 때, "F" 를 반환하는 것은 어떤 의미인지 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +    func joinWords(first index1: Int, second index2: Int, this word: [Character]) -> [Character] {
`extension` 으로 따로 빼서 `joinWords` 메서드를 구현하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +        var usefulValue = [Character]()
`useful` 이라는 단어의 의미가 개발자 마다 모호할 수 있을 것 같습니다. 의견이 궁금합니다!
'유용한' 이라는 의미보다 더 구체적인 이름을 지어볼 수 있을까요?

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +        }
직접 인덱스 위치를 구하여 문자열을 분리하기보다는(너무 어렵게 접근하지 않았나 싶었습니다!)
사용자에게 문자열을 입력 받은 후,
특수문자 `/` 를 기준으로 [이름] / [나이] / [연락처] 를 분리해보는 것 부터 시작해보면 어떨까요?
String 의 `split` 이나 `components` 메서드를 활용해보면 좋을 것 같습니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +struct ContactInfo {
`ContactInfo` 이름도 좋지만 축약어 대신 전체 이름을 사용하도록 연습 해보는 건 어떨까요?
[Swift API Design Guide](https://www.swift.org/documentation/api-design-guidelines/#use-terminology-well) 파트를 참고해보면 좋을 것 같습니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/Converter.swift
> +class Converter {
`Converter` 타입을 클래스로 선언하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/Detector.swift
> +
의도적으로 삽입하신 공백인가요? `excludeSpaceWord` 메서드의 `for 문` 과 다르게 작성되어 있어서 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/Detector.swift
> +}
현재 사용하고 있지 않은 코드로 보입니다. 사용하지 않는 코드는 제거하는 것이 어떨까요?

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/Detector.swift
> +class Detector {
`Detector` 타입을 클래스로 선언하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Model/Checker.swift
> +class Checker {
`Checker` 타입을 클래스로 선언하신 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Storage/PrintMessage.swift
> +}
문자열을 따로 모아서 관리하셨네요. 좋습니다!👍
`CustomStringConvertible` 프로토콜도 사용해보셨네요!🥳

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Storage/RegularExpression.swift
> +        return "\(self.rawValue)"
String 타입인 `rawValue` 를 Sting Interpolation 을 통해 한번 더 감싸서 표현한 이유가 궁금합니다!

2022-12-26 11:29 UTC, zdodev commented on ContactManager/ContactManager/Protocol/InputPossible.swift
> +    func getUserInputValues() -> String
메서드 이름에 `get` 을 사용하지 않더라도 의미가 전달될 것 같습니다. 지금도 좋습니다!
의견이 궁금합니다!

2022-12-27 00:59 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/Detector.swift
> +
코드 작성 중 실수로 작성된 공백입니다! 해당 부분 수정하여 반영하도록 하겠습니다! 🤓

2022-12-27 01:03 UTC, bomyuniverse commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +struct ContactInfo {
Info라는 단어를 많이 쓰다보니 해당 단어가 축약어일 것이라는 생각을 못하고 사용했네요 😢 
Swift API Design Guide에 나와있는 것처럼 `간결함보다는 명확성이 중요하다.`는 점을 상기시켜 구조체 이름을 수정 및 반영하겠습니다!

2022-12-27 01:10 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +            let phoneNumberString = checker.checkCorrectWord(target: convertor.convertToString(phoneNumberWord))
`check`라는 객체를 통해 올바른 String값 (Ex. name = jason)이 들어왔을 때 올바른 입력에 맞는 출력문(print)을 사용하기위해 프로퍼티화 하였습니다. 아직 출력문을 작성하는 부분까지 진행을 못하여 warning이 발생하는 부분이라 추후 개선하여 반영될 것 같습니다!

2022-12-27 01:10 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +extension ContactManager: InputPossible {
처음에 예상했던 부분은 Protocol Default Implimentations(프로토콜 초기구현)을 통해 진행하려고 했었으나
개인역량차가 조금 있어 ContactManager가 입력을 받을 수 있는 역할(protocol)을 할 수 있다는 느낌을 주려고 작성하였습니다.
또한 제가 코드를 작성하는데 있어 프로토콜을 채택하여 작성하는 부분을 extenstion으로 구역을 나누어 작성하면 그 영역에서는 해당
프로토콜의 내용만 구현하고 수정할 수 있어서 가독성을 부분에서 좋다고생각해 작성하였습니다.

2022-12-27 01:15 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +            return "F"
위 `identifier` 프로퍼티의 임의의 값을 변경하여 ("" -> "F") 반복문이 실행할 수 있도록 작성하였습니다.
위 답변에서 말씀드린것처럼 수정할 예정입니다!

2022-12-27 01:16 UTC, bomyuniverse commented on ContactManager/ContactManager/main.swift
> +class ContactManager {
`final class`로 최상위 클래스임을 명시하면 main.swift 파일에서도 사용하는 데에 문제가 없을 것이라 생각하여 해당 파일에서 작성하였습니다.
Buddy들의 조언에 따르면 main.swift 파일은 앱이 실행되는 부분이라고 하여 해당 파일을 깔끔하게 유지하기 위해 정의된 타입을 파일로 분리하여 작업 예정입니다! 👍 수정하여 반영하도록 하겠습니다!

2022-12-27 01:25 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +    func joinWords(first index1: Int, second index2: Int, this word: [Character]) -> [Character] {
기존에는 `converter`에서 이 메서드를 작성하려고 하였습니다.
하지만 `converter` 의 역할이 타입을 변경하는 (String -> Character 또는 Character -> String) 일만 하게끔 만들려고했습니다.
그런데 `joinWords` 메서드는 반환값이 입력값(word)과 타입이 동일하여 역할을 따로 구분해야할지 고민이 좀 됩니다..🤔
하여 당시 작성 시 extension을 사용하여 가독성 및 `contactManager`에서 분리할지 고민이 되다보니 따로 빼서 작업하게 되었습니다.

2022-12-27 01:26 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +        var usefulValue = [Character]()
사전적의미로 고민을 해보았습니다.
`useful`이 뭔가 의미전달로는 `사용할 수 있는`이라고 생각이 되어 네이밍을 위와 같이 작성하게되었습니다.
더 좋은 네이밍이 있을까요?? 😅

2022-12-27 01:29 UTC, JasonLee0223 commented on ContactManager/ContactManager/main.swift
> +        }
넵 알겠습니다! 지금은 Index out of range 문제를 해결하였는데 소대가 알려주신 방법으로도 한 번 진행해보겠습니다!
감사합니다!

2022-12-27 01:33 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Detector.swift
> +}
넵 맞습니다! 위에 joinWords와 동일한 기능을 나타내려고 했던 코드여서 제거해야하는 부분입니다!
수정하여 반영하겠습니다!

2022-12-27 01:36 UTC, JasonLee0223 commented on ContactManager/ContactManager/Storage/RegularExpression.swift
> +        return "\(self.rawValue)"
실수한 부분이네요..;; `return \(self.rawValue)`로 수정하여 반영하겠습니다.

2022-12-27 01:39 UTC, JasonLee0223 commented on ContactManager/ContactManager/Protocol/InputPossible.swift
> +    func getUserInputValues() -> String
감사합니다! 이전에 API 가이드라인에서 `get`은 값을 얻어오는 행위만 진행할 때 사용한다고 했던 것 같습니다..^^;;
이에 반해 String값을 반환하는 부분이 있어 `get`을 붙일지 한 번 더 고민해보겠습니다! ㅎㅎ

2022-12-27 01:43 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Detector.swift
> +class Detector {
당일 코드를 좀 급하게 작성하다보니 `struct` 과 `class` 타입에 대한 고민을 오래하지 못하게 진행하여 아쉬웠던 부분입니다...
class로 선언할 때는 아래와 같은 생각이 들어 작성하였습니다.
1. 이후 step을 진행할 때 해당 클래스에 프로퍼티가 생성되어 initializer에 대한 고민도 같이 해보고자 하였습니다.
2. 당시 해당 파일에 구현할 내용이 메서드만 작성하려고 하다보니 타입에 대한 고민을 다음 step에서 해보고자 하였습니다.

2022-12-27 01:43 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Checker.swift
> +class Checker {
위와 동일한 이유로 작성하게되었습니다...!

2022-12-27 01:50 UTC, JasonLee0223 commented on ContactManager/ContactManager/Model/Converter.swift
> +class Converter {
위와 동일한 이유입니다...!

2022-12-27 02:02 UTC, bomyuniverse commented on ContactManager/ContactManager/main.swift
> +    func processStart() {
첨부해주신 Swift API Design Guide 문서를 참고하여 해당 메서드에 적합한 두 가지 네이밍 방법을 발견하였습니다.
1.  Swift API Design Guide 문서의 `Those without side-effects should read as noun phrases` 부분을 참고한 결과, 단순히 프로세스가 시작되는 함수이므로 side-effects가 없는 메서드로 판단하였습니다. 이 부분을 적용하는 경우 `process`로 네이밍 변경 예정입니다.
2. 소대가 권장해주신 방법인 동작 또는 행위를 나타내는 단어를 메서드 이름 앞에 작성하는 것입니다. 공식 문서 중`When the operation is naturally described by a verb, use the verb’s imperative for the mutating method and apply the “ed” or “ing” suffix to name its nonmutating counterpart.` 부분을 참고하여, 기능이 동사로 자연스럽게 설명된다고 판단하였습니다. 이 부분을 적용하는 경우 `startProcess`로 네이밍 변경 진행 예정입니다.

우선, 소대가 권장해주신 방법대로 2번의 방법을 사용하여 진행하려고 합니다.
혹시 두 방법 중 어떤 것을 사용해도 상관이 없을 지, 둘 중 추천하는 네이밍 방법이 있다면 어떤 것인지 알려주실 수 있을까요?
감사합니다!! 🙇

2022-12-27 12:45 UTC, zdodev commented on ContactManager/ContactManager/Model/ContactInformation.swift
> +struct ContactInformation {
축약어를 바꿔보셨네요.👍

2022-12-27 12:45 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +ContactManager().startProcess()
`main` 이 깔끔해졌어요!😲

2022-12-27 12:45 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +    func processStart() {
개인적으로 메서드 네이밍을 할 때 동사를 포함한 이름을 많이 사용합니다. 어떤 행위를 수행하는 지 명시하면 가독성이 더 좋아진다는 생각입니다.(무조건은 아닙니다!)
지금 같은 경우 `process` 만 사용한 이름은 (어떤 프로세스?)의미가 추상적이지 않았나 싶었습니다. 그래서 `startProcess` 를 사용할 것 같습니다!

2022-12-27 12:47 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +extension ContactManager: InputPossible {
좋은 생각입니다!

2022-12-27 12:56 UTC, zdodev commented on ContactManager/ContactManager/main.swift
> +        var usefulValue = [Character]()
사용자의 입력 값의 구성 요소는 Contact 정보이고, `usefulValue` 에 담기는 정보는 그 해당 요소만을 담는 역할을 한다고 보면
`ContactElement` 또는 `ContactComponent` 도 괜찮다는 생각입니다.🤔 의견이 궁금합니다!

2022-12-27 13:06 UTC, zdodev approved these changes
안녕하세요. @JasonLee0223 , @bomyuniverse !

피드백이 반영되어야 하는 부분에 코드 수정이 잘 이루어졌습니다!
그리고 궁금증에 대하여 자신만의 생각을 잘 얘기해주신 점이 좋았습니다.👍👍

다음 스텝에서는 아직 남아있는 고민과 기능 동작에 더 신경쓰면 좋을 것 같습니다!

스텝1 진행하시느라 고생하셨습니다~🥳

2022-12-27 13:07 UTC, merged