PhoneBookManager [STEP 1] Mason, d.o
tasty-code/ios-contact-manager pull request #3
Opened 2022-12-23 06:57 UTC by doshkor

@jryoun1

안녕하세요 Jake🤗
[ mason && d.o ] - 연락처 관리 앱 1단계 구현 과제 리뷰요청 드립니다!

### ⚠️ 프로젝트 수행시 제약사항

- 코드에 느낌표(!)를 사용하지 않습니다.
- **Swift API Design Guidelines 의 문서대로 코드를 작성합니다.**
- 들여쓰기는 3번을 초과하지 않습니다.
- 한 커밋의 코드 단위에 대해 고민하여 진행합니다.

### ✅ 1단계 구현 요구사항 - 사용자 입력 수신 및 검증

입력받은 내용을 검증하여 사용자에게 안내문을 출력합니다

- 사용자의 입력을 받는 동작을 구현합니다.
    - 한글 자소분리 현상은 과제 수행 중 해결해야 하는 문제가 아닙니다.
    - 사용자 이름 입력은 한글이 아닌, 영어로만 진행해주세요.
- 올바른 사용자 입력 형태 : `[이름] / [나이] / [연락처]` / `[이름]/[나이]/[연락처]`
    - `이름`: 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다
    - `나이`: 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.
    - `연락처`: 중간에 - 로 구분하며, - 는 두 개 존재해야합니다. - 를 제외하고 숫자는 9자리 이상이어야 합니다.
- **올바른 사용자 입력 예시**
    - james / 30 / 05-343-2334
    - ja mes / 30 / 013-3343-2343
    - james/30/013-3432-3433
- **올바르지 않은 사용자 입력 예시**
    - james / 서른 / 05-343-2334
    - ja mes / 30 / 01333432343
    - james/30세/013 3432 3433
    - james/013-3423-4432/30

### **🧑🏼‍💻 작업 목록**

- 사용자 입력 받기
- 사용자 입력 검증
    - 실패 시: 에러 메세지 출력
    - 성공 시: 사용자 입력 정보 출력

### **💭 학습 키워드**

- 올바르게 네이밍 하기 - [Swift API Design Guidelines] Naming 파트
- 에러 타입 구현 및 에러 핸들링
- Swift 스럽게 코드 작성하기
    - guard 문 사용을 통한 Early-Exit
    - enum의 활용

### **🤔 고민과 해결**

1. 사용자의 “이름/나이/전화번호” 입력을 받아 포맷을 1차 검증하고 슬래시를 기준으로 자르는 함수를 작성하였습니다.
    - 처음에는 로직을 단순히 사용자의 입력의 모든 공백을 제거하고, ”/” 를 기준으로 자르고 배열화 하였지만,
    프로젝트 요구사항이 “이름/나이/연락처” 이거나 “이름 / 나이 / 연락처” 와 같이 두 가지 포맷만을 허용한다는 것을 알고 로직을 변경하였습니다.
    - 포맷을 검증하는 함수를 중첩 함수로 작성하였는데, 이렇게 작성하는 것이 적절한 방식인지 궁금합니다.
    - 또한 “역할” 을 나타내게 함수명을 작성하려고 했는데 역할을 기준으로 명확히 함수를 나누는 것이 쉽지 않은 것을 느꼈습니다.
    - 코드 전반적으로 네이밍이 적절하지 않은 부분이 있다면 많은 피드백 부탁드립니다!
    
    ```swift
    enum InputManager {
        static func splitBySlash(from input: String) throws -> [String] {
            func checkFormat(for inputArray: [String]) -> Bool {
                return inputArray.count == 3
                    && inputArray[0].hasWhiteSpaceAtStartOrEnd() == false
                    && inputArray[1].hasWhiteSpace() == false
                    && inputArray[2].hasWhiteSpace() == false
            }
            
            var splitedInput = input.split(separator: " / ").map { String($0) }
            if checkFormat(for: splitedInput) {
                return splitedInput
            }
            
            splitedInput = input.split(separator: "/").map { String($0) }
            if checkFormat(for: splitedInput) {
                return splitedInput
            }
            
            throw InputError.invalidInput
        }
    ...
    ```
    
2. 동작을 위한 run 함수에서, 유저 input을 받고 InputManager 의 static func 들을 활용 해 
input 을 배열로 나누고 그 배열들을 또 InputManager 로 넘겨서 name, age, phoneNumber 를 받아오는 구조입니다. 
    - 이러한 구조가 적절한지 궁금합니다. 
    (InputMager에 input String 만 넘기면, splitBySlash, getName, getAge… 와 같은 함수를 호출하는 하나의 함수가 있는 구조가 나을까요? → 그렇다면 함수명은 어떻게 짓는게 좋을까요?)
    
    ```swift
    struct PhoneBookManager {
        func run() {
            ConsoleView.printInputMessage()
            let userInput = ConsoleView.userInput()
            
            do {
                guard !userInput.isEmpty else { throw InputError.emptyInput }
                
                let inputArray = try InputManager.splitBySlash(from: userInput)
                
                let name = InputManager.getName(from: inputArray)
                let age = try InputManager.getAge(from: inputArray)
                let phoneNumber = try InputManager.getPhoneNumber(from: inputArray)
    
                ConsoleView.printInitialInputInfo(name: name, age: age, phoneNumber: phoneNumber)
            } catch {
                print(error.localizedDescription)
            }
        }
    }
    ```
    
3. 검증에 활용하기 위한 String extension 을 구현하였습니다.
    - 공백을 제거하는 함수는 mutating 하지 않기 때문에 “ed”, “ing” 방식으로 removing 작성하였는데 적절한지 궁금합니다.
    - “hasWhiteSpaceAtStartOrEnd” 라는 이름이 너무 길어지는 듯 한데, 더 좋은 작명이 있을지 고민입니다.
    
    ```swift
    extension String {
        func removingWhiteSpaces() -> String {
            return self.filter { $0 != " " }
        }
        
        func hasWhiteSpace() -> Bool {
            return self.rangeOfCharacter(from: .whitespaces) != nil
        }
        
        func hasWhiteSpaceAtStartOrEnd() -> Bool {
            return self.hasPrefix(" ") || self.hasSuffix(" ")
        }
    }
    ```

2022-12-26 12:47 UTC, jryoun1 requested changes
두 분 모두 step1 고생하셨습니다! 
코드 리뷰에는 정답은 없으니, 궁금하신 점이나 제가 남긴 코멘트가 잘 이해되지 않는 부분 등은 댓글로 같이 의견 나누면 좋을 것 같아요 🙂 ㅎㅎ 

우선 코드와 작성해주신 pr에서 많은 노력과 고민의 흔적이 보이네요 👏💯
전반적으로 잘 작성해주신 것 같아요! 
다만 몇 가지 아쉬운 부분들이 있어서 코멘트로 남겨두었습니다. 확인 부탁드려요~ 
또한 현재 제가 프로젝트를 받아서 돌려봤을 때는 빌드가 안 되는 것으로 확인했는데, 두 분께서는 정상적으로 동작하는지 확인부탁드릴게요🙏🏻

----

질문해주신 것에 대한 답변입니다.
1. 코드 리뷰에 남겨두었습니다. 
2. 이것도 코드 리뷰에 남겨져 있습니다!
현재 작성해주신 여러 manager들이 있는데, 각각의 매니저들의 역할이 어떤 것인지 더 명확하면 좋을 것 같습니다! 예를 들면 inputManager의 역할은 어디까지 일까요? 

- 사용자로부터 입력만 받기
- 사용자로부터 입력을 받고, 입력을 검증한다 
- 사용자로부터 입력을 받고, 입력을 검증한 뒤, 이를 name, age, phoneNumber로 분리까지 한다

이런식으로 해당 manager가 어디까지 역할을 할 것인지에 따라서 네이밍은 다 다를 것이라고 생각이 드네요.

3. ed, ing 네이밍에 대해서는 코드리뷰에 남겨두었습니다 🙏🏻
hasWhiteSpaceAtStartOrEnd 네이밍의 경우에는 명확하게 어떤 역할을 하는 것인지 잘 나타내고 있는 것 같습니다! 👍🏻

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/Extensions.swift
> +//  Extensions.swift
여기도 동일합니다! 
어떤 extension들이 이 파일에 들어있는지 전혀 예상이 가지 않을 것 같아요.
어떤 타입을 Extension해서 모아둔다면 Extension+String, 혹은 String+Extension이라고 파일명을 짓긴합니다.

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/Extensions.swift
> +    func removingWhiteSpaces() -> String {
함수명은 동사로 시작합니다! 
[문서](https://www.swift.org/documentation/api-design-guidelines/#naming)에서 예시들을 참고해보면 좋을 것 같아요 🙏🏻

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/Extensions.swift
> +    func hasWhiteSpace() -> Bool {
has를 prefix로 가지고 반환형이 Bool인 함수의 네이밍 아주 좋네요 👏

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputError.swift
> +//  ErrorMessage.swift
여기도 동일합니다🙏🏻

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputError.swift
> +enum InputError: String, LocalizedError {
LocalizedError 프로토콜을 채택하셨군요 👏
해당 프로토콜은 무엇을 위해서 채택하셨을까요?

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/main.swift
> +pbManager.run()
phoneBookManager 객체를 PhoneBookManager에서 생성해서 run해도 될 것 같은데, 
main이라는 파일을 따로 만든 이유가 있을까요? 🙋‍♂️

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        var splitedInput = input.split(separator: " / ").map { String($0) }
🚨 현재 split(separator:) 메서드를 호출할 때 넘겨주는 매개변수가 잘못되어서 프로그램이 실제로 동작하고 있지 않은 것 같습니다. 확인부탁드려요 🙏🏻

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        func checkFormat(for inputArray: [String]) -> Bool {
Bool 타입이 반환형일때는 `is~`, `has~` prefix가 붙는게 더 좋아보입니다! 
해당 함수를 따로 구현하지 않고 splitBySlash함수 내부에 중첩한 이유도 궁금합니다 🙋‍♂️

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        throw InputError.invalidInput
throw 사용해보셨군요 👏

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        return array[0].removingWhiteSpaces()
만약 여기서 0번째가 없다면 해당 프로그램은 어떻게 될까요? 
배열에서 index를 사용해서 직접 접근하는 것은 위험합니다. 
hint: [배열에 구현 되어 있는 메서드](https://developer.apple.com/documentation/swift/array)들 중에서 안전하게 접근할 수 있는 것이 무엇인지 찾아보면 어떨까요?

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        guard let age = Int(array[1]), 0..<1000 ~= age else {
🚨 index를 통한 직접 접근! 
여기도 개선해볼까요?

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        let phoneNumber = array[2]
여기도 동일합니다 🚨

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +    static func splitBySlash(from input: String) throws -> [String] {
이 함수는 네이밍과는 다르게 역할이 2개로 보입니다. 개선이 필요할 것 같아요 🙏🏻

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        let phoneRegEx = #"^\d{2,3}-\d{3,4}-\d{4}$"#
정규표현식도 사용하셨군요 👍🏻💯

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/PhoneBookManager.swift
> +struct PhoneBookManager {
struct와 enum을 사용하신 기준이 궁금합니다 🙋‍♂️

2022-12-26 12:47 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/PhoneBookManager.swift
> +    func run() {
run이라는 함수명은 c언어에서 많이 사용되는 함수명으로 보입니다.
Swift에서는 잘 사용하지 않습니다! 

추가로 PhoneBookManager의 역할은 무엇인가요? 🙋‍♂️

2022-12-27 01:21 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/ConsoleView.swift
> +//  IOManager.swift
IOManager 에서 ConsoleView 로 파일명을 변경하여 주석의 파일명과 일치하지 않았습니다.

2022-12-27 01:21 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/ConsoleView.swift
> +enum ConsoleView {
파일명 ConsoleView 가 명확하지 않아 OutputManager 로 변경하였습니다.

2022-12-27 01:53 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/ConsoleView.swift
> +    static func printInitialInputInfo(name: String, age: Int, phoneNumber: String) {
인스턴스를 생성하지 않고, 함수를 사용할 수 있게 하는 키워드가 static func 인데 
해당 타입 메서드의 경우엔 저장 속성에 대한 접근을 필요로 하지 않고, 
단순히 파라미터 3개를 받아 유저에게 콘솔창으로 출력 해 주는 순수함수이기 때문에 static func 로 구현하였습니다 :)

2022-12-27 02:01 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/Extensions.swift
> +    func removingWhiteSpaces() -> String {
Swift API Guideline - naming 파트의 "Name functions and methods according to their side-effects"
에서 sort(), sorted() 의 차이에 대해 공부하다가 non-mutating 함수이기 때문에 ed/ing 형태로 명명하는 것이 나을 것 같아 수정하였었는데요,,!
말씀하신 걸 생각 해 봤을 때 ing 형태로 작성하게 되면 동사가 아니기 때문에 가시성이 떨어지는 문제가 있을 수 있을 것 같습니다.!
혹시 어떻게 생각하시는지 여쭤봐도 될까요~?

2022-12-27 02:08 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/InputError.swift
> +enum InputError: String, LocalizedError {
errorDescription 를 정의해서 error.localizedDescription 으로 에러 문구 출력을 할 수 있게 하기 위해 채택하였습니다!

이전에는 그냥 Error 타입을 채택해, printError 함수를 구현하고 
호출하는 do - catch 부분에서 InputError 타입일 경우에 printError() 를 호출하게 분기 처리를 따로 해줘야 했는데, 더 나은 방법이 없을까 알아보다 알게 되었습니다 :)

2022-12-27 02:51 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        var splitedInput = input.split(separator: " / ").map { String($0) }
split(separator:) 에 공백이 포함된 “ / “ 를 넘겼는데, 빌드 타겟을 13.0 미만으로 바꾸니 해당 현상이 재현되었습니다.

separator 파라미터에 두 글자 이상을 넘길 때에 생기는 문제인데 기본 split 메서드는 한 글자만 허용했었고, 
두 글자 이상 허용하는 메서드는 macOS 13.0 이후에 추가되었다는 것을 알게 되었습니다.
split 대신 components 를 사용하기로 했고, 두 메서드의 차이에 대해서 학습하였습니다 :D

2022-12-27 04:35 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        func checkFormat(for inputArray: [String]) -> Bool {
splitBySlash -> parse
checkFormat -> isValidFormat
으로 함수명을 수정하였습니다.

중첩 함수로 구현한 이유는, 파싱 이라는 과정 안에 올바른 포맷인지 검증하는 과정이 포함되어 있다고 생각했고 
해당 검증함수는 오직 파싱 함수만을 위해 사용되기에 중첩 함수로 구현하는 것이 좋지 않을까? 라는 생각이 들었습니다.

그럼에도 함수를 밖으로 따로 분리해야 한다면 isValidFormatToParse 같은 식으로 함수이름에 역할을 분명히 해줘야 할 것 같다는 생각이 듭니다.

밖으로 따로 분리하는 것의 기준을 재사용성이 있는지와 가시성을 해치는지 아닌지를 생각했는데.. 혹시 그 외의 기준이 있을까요? 
결론적으로 따로 분리하는 것이 더 나은 코드일까요~?

2022-12-27 05:17 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        return array[0].removingWhiteSpaces()
```
extension Array {
    subscript(safe index: Int) -> Element? {
        return indices ~= index ? self[index] : nil
    }
}
```
Extension을 추가하고, 옵셔널 바인딩 통해 값을 사용하도록 수정해봤습니다.

2022-12-27 05:19 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        return array[0].removingWhiteSpaces()
```
    static func getName(from array: [String]) throws -> String {
        guard let name = array[safe: 0] else {
```

2022-12-27 05:19 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        guard let age = Int(array[1]), 0..<1000 ~= age else {
```
    static func getAge(from array: [String]) throws -> Int {
        guard let safeValue = array[safe: 1],
              let age = Int(safeValue),
              0..<1000 ~= age else {
```

2022-12-27 05:19 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        let phoneNumber = array[2]
```
    static func getPhoneNumber(from array: [String]) throws -> String {
        let phoneRegEx = #"^\d{2,3}-\d{3,4}-\d{4}$"#
        guard let phoneNumber = array[safe: 2],
              phoneNumber.range(of: phoneRegEx, options: .regularExpression) != nil else {
```

2022-12-27 06:07 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/PhoneBookManager.swift
> +struct PhoneBookManager {
저장 속성을 갖지 않고 `static func` 들만 갖고 있는 타입은 굳이 인스턴스화를 하지 않게끔 `enum` 으로 구현하였습니다.
해당 `PhoneBookManager` 를 `struct` 로 구현한 이유는 차후 연락처 모델의 데이터를 저장 속성으로 갖게 될 것 같아 구조체로 구현하였습니다.
> 구조체는 `mutating` 을 매번 함으로서 매번 값을 복사하게 되므로 `final class` 로 구현해야 하나 고민이 있는데, 퍼포먼스 차이를 찾아본 결과 큰 차이가 없고 오히려 struct 가 빠를 때도 있다는 의견이 있어 고민이 됩니다.
공식 문서의 해당 내용을 바탕으로는 struct 가 낫겠다고 생각했습니다!
- Use `structures` by **default**. 
- Use `classes` when you need **Objective-C** interoperability.
- Use `classes` when you need to control the identity of the data you’re modeling.
- Use `structures` along with protocols to adopt behavior by sharing implementations.

2022-12-27 06:09 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +    static func splitBySlash(from input: String) throws -> [String] {
위에서 답변드렸습니다! :)

2022-12-27 06:21 UTC, doshkor commented on PhoneBookManager/PhoneBookManager/main.swift
> +pbManager.run()
프로젝트를 command line tools 파일로 생성하였을 때 실행파일이 main.swift 로 되어있는 것으로 보입니다. 또한 main 파일 이름을 수정시 실행이 되지 않습니다

수정방향
 -> run() 로직을 main.swift 파일에 옮겼습니다.
 -> PhoneBookManager 에는 추후 필요한 연락처 데이터를 다루는 구조체로 구현할 예정입니다.

2022-12-27 06:22 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        var splitedInput = input.split(separator: " / ").map { String($0) }
`PhoneBookManager` 의 역할은 사용자가 입력한 연락처 정보를 저장하고 관리하는 컨트롤러 구조체로 구현하려 하였으나,
현재 단계에서는 불필요한 듯 하여 실행 로직을 프로그램의 실행지점인 `main.swift` 의 `execute()` 함수로 구현하였습니다.

현재 단계의 요구사항에서 역할을 설명하지 못하는 코드는 불필요한 코드라 생각이 되고, 
필요한 로직 만큼만 구현하는 것이 중요하다고 것에 대해 생각 해 보게 되었습니다 :)

2022-12-27 07:01 UTC, qwerty3345 commented on PhoneBookManager/PhoneBookManager/PhoneBookManager.swift
> +    func run() {
PhoneBookManager 의 역할은 사용자가 입력한 연락처 정보를 저장하고 관리하는 컨트롤러 구조체로 구현하려 하였으나,
현재 단계에서는 불필요한 듯 하여 실행 로직을 프로그램의 실행지점인 main.swift 의 execute() 함수로 구현하였습니다.

현재 단계의 요구사항에서 역할을 설명하지 못하는 코드는 불필요한 코드라 생각이 되고,
필요한 로직 만큼만 구현하는 것이 중요하다고 것에 대해 생각 해 보게 되었습니다 :)

2022-12-27 07:27 UTC, qwerty3345 commented
안녕하세요 제이크! @jryoun1 
정성스럽게 써주신 리뷰 덕분에 많은 부분을 고민 해 보고, 공부해볼 수 있게 되었습니다 🙂
수정 사항 반영 하였고, 질문들은 코멘트에 다시 코멘트 남겨 드렸습니다!
그리고 코멘트에 질문드린 사항들을 따로 정리해서 보내드립니다 :) (코멘트와 동일합니다)

1. static을 써보셨군요 👏 언제 static func를 사용할까요?
    - 인스턴스를 생성하지 않고, 함수를 사용할 수 있게 하는 키워드가 static func 인데해당 타입 메서드의 경우엔 저장 속성에 대한 접근을 필요로 하지 않고,단순히 파라미터 3개를 받아 유저에게 콘솔창으로 출력 해 주는 `순수함수`이기 때문에 static func 로 구현하였습니다 :)
    - +) 다음 스텝에 가게 되어서, 연락처 모델을 구조체로 구현한다면저장 속성인 name, age, phoneNumber 을 String 문자열로 적절히 변환해주는 description 과 같은 계산 속성으로 구현하는 것이 좋을 것 같다는 생각을 했습니다.
2. 함수명은 동사로 시작합니다! [[문서](https://www.swift.org/documentation/api-design-guidelines/#naming)](https://www.swift.org/documentation/api-design-guidelines/#naming)에서 예시들을 참고해보면 좋을 것 같아요 🙏🏻
    
    ```swift
    extension String {
        func removingWhiteSpaces() -> String {
    ```
    
    - Swift API Guideline - naming 파트의 "Name functions and methods according to their side-effects" 에서 `sort()`, `sorted()` 의 차이에 대해 공부하다가 non-mutating 함수이기 때문에 ed/ing 형태로 명명하는 것이 나을 것 같아 수정하였었는데요,,!
    말씀하신 걸 생각 해 봤을 때 ing 형태로 작성하게 되면 동사가 아니기 때문에 가시성이 떨어지는 문제가 있을 수 있을 것 같습니다.! 
    혹시 어떻게 생각하시는지 여쭤봐도 될까요~?
3. LocalizedError 프로토콜을 채택하셨군요 👏 해당 프로토콜은 무엇을 위해서 채택하셨을까요?
    - `public var errorDescription: String?` 를 정의해서 `error.localizedDescription` 으로 에러 문구 출력을 할 수 있게 하기 위해 채택하였습니다!
    - 이전에는 그냥 Error 타입을 채택해, `printError` 함수를 구현하고호출하는 do - catch 부분에서 InputError 타입일 경우에 printError() 를 호출하게 분기 처리를 따로 해줘야 했는데, 더 나은 방법이 없을까 알아보다 알게 되었습니다 :)
    - +질문) `InputError` 타입을 정의할 때 에러 메시지를 `String rawValue` 로 넣어줬는데,다른 예시를 찾아보다 보니 `errorDescription` 을 구현할 때 `switch self` 를 통해서 각 케이스마다 에러 메시지를 return 하게 구현한 방식도 많은 걸 발견했습니다.두 가지 중에 어떤 것을 채택하느냐는 error 메시지를 출력하는 경우 외에 rawValue 를 따로 사용할 일이 있느냐, 없느냐 정도로 생각하는 것이 맞을까요? 의견이 궁금합니다 :)
        
        > 자답) 공부하다가,에러의 경우 서버 응답 코드와 rawValue를 매칭해서 사용하곤 하기 때문에 rawValue에 출력 문구를 사용하는건 지양하는게 좋다는 의견을 알게 되었습니다!
        > 
4. 🚨 현재 split(separator:) 메서드를 호출할 때 넘겨주는 매개변수가 잘못되어서 프로그램이 실제로 동작하고 있지 않은 것 같습니다. 확인부탁드려요 🙏🏻
    - `split(separator:)` 에 공백이 포함된 “ / “ 를 넘겼는데, 빌드 타겟을 13.0 미만으로 바꾸니 해당 현상이 재현되었습니다.
    - `separator` 파라미터에 두 글자 이상을 넘길 때에 생기는 문제인데 기본 `split` 메서드는 한 글자만 허용했었고,두 글자 이상 허용하는 메서드는 macOS 13.0 이후에 추가되었다는 것을 알게 되었습니다.`split` 대신 `components` 를 사용하기로 했고, 두 메서드의 차이에 대해서 학습하였습니다 :D
5. Bool 타입이 반환형일때는`is~`, `has~` prefix가 붙는게 더 좋아보입니다!
해당 함수를 따로 구현하지 않고 splitBySlash함수 내부에 중첩한 이유도 궁금합니다 🙋‍♂️
    - `splitBySlash` -> `parse`   
    `checkFormat` -> `isValidFormat`으로 함수명을 수정하였습니다.
    - 중첩 함수로 구현한 이유는, 파싱 이라는 과정 안에 올바른 포맷인지 검증하는 과정이 포함되어 있다고 생각했고해당 검증함수는 오직 파싱 함수만을 위해 사용되기에 중첩 함수로 구현하는 것이 좋지 않을까? 라는 생각이 들었습니다.
    - 그럼에도 함수를 밖으로 따로 분리해야 한다면 isValidFormatToParse 같은 식으로 함수이름에 역할을 분명히 해줘야 할 것 같다는 생각이 듭니다.
    - 밖으로 따로 분리하는 것의 기준을 재사용성이 있는지와 가시성을 해치는지 아닌지를 생각했는데.. 혹시 그 외의 기준이 있을까요?결론적으로 따로 분리하는 것이 더 나은 코드일까요~?
6. 만약 여기서 0번째가 없다면 해당 프로그램은 어떻게 될까요?
배열에서 index를 사용해서 직접 접근하는 것은 위험합니다.
hint: [[배열에 구현 되어 있는 메서드](https://developer.apple.com/documentation/swift/array)](https://developer.apple.com/documentation/swift/array) 들 중에서 안전하게 접근할 수 있는 것이 무엇인지 찾아보면 어떨까요?
    - `Extension`을 추가하고, 옵셔널 바인딩 통해 값을 사용하도록 수정해봤습니다.
    
    ```swift
    extension Array {
        subscript(safe index: Int) -> Element? {
            return indices ~= index ? self[index] : nil
        }
    }
    ```
    
7. struct와 enum을 사용하신 기준이 궁금합니다 🙋‍♂️
    - 저장 속성을 갖지 않고 `static func` 들만 갖고 있는 타입은 굳이 인스턴스화를 하지 않게끔 `enum` 으로 구현하였습니다.해당 `PhoneBookManager` 를 `struct` 로 구현한 이유는 차후 연락처 모델의 데이터를 저장 속성으로 갖게 될 것 같아 구조체로 구현하였습니다.
        
        > Use structures by default.
        Use classes when you need Objective-C interoperability.
        Use classes when you need to control the identity of the data you’re modeling.
        Use structures along with protocols to adopt behavior by sharing implementations.
        > 
    - 구조체는 `mutating` 을 매번 함으로서 매번 값을 복사하게 되므로 `final class` 로 구현해야 하나 고민이 있는데, 퍼포먼스 차이를 찾아본 결과 큰 차이가 없고 오히려 struct 가 빠를 때도 있다는 의견이 있어 고민이 됩니다.공식 문서의 해당 내용을 바탕으로는 struct 가 낫겠다고 생각했습니다!

2022-12-27 07:57 UTC, qwerty3345 commented
안녕하세요 제이크! @jryoun1
정성스럽게 써주신 리뷰 덕분에 많은 부분을 고민 해 보고, 공부해볼 수 있게 되었습니다 🙂
수정 사항 반영 하였고, 질문들은 코멘트에 다시 코멘트 남겨 드렸습니다!
그리고 코멘트에 질문드린 사항들을 따로 정리해서 보내드립니다 :) (코멘트와 동일합니다)

static을 써보셨군요 👏 언제 static func를 사용할까요?

인스턴스를 생성하지 않고, 함수를 사용할 수 있게 하는 키워드가 static func 인데해당 타입 메서드의 경우엔 저장 속성에 대한 접근을 필요로 하지 않고,단순히 파라미터 3개를 받아 유저에게 콘솔창으로 출력 해 주는 순수함수이기 때문에 static func 로 구현하였습니다 :)
+) 다음 스텝에 가게 되어서, 연락처 모델을 구조체로 구현한다면저장 속성인 name, age, phoneNumber 을 String 문자열로 적절히 변환해주는 description 과 같은 계산 속성으로 구현하는 것이 좋을 것 같다는 생각을 했습니다.
함수명은 동사로 시작합니다! [[문서](https://www.swift.org/documentation/api-design-guidelines/#naming)]([https://www.swift.org/documentation/api-design-guidelines/#naming)에서](https://www.swift.org/documentation/api-design-guidelines/#naming)%EC%97%90%EC%84%9C) 예시들을 참고해보면 좋을 것 같아요 🙏🏻

extension String {
    func removingWhiteSpaces() -> String {
Swift API Guideline - naming 파트의 "Name functions and methods according to their side-effects" 에서 sort(), sorted() 의 차이에 대해 공부하다가 non-mutating 함수이기 때문에 ed/ing 형태로 명명하는 것이 나을 것 같아 수정하였었는데요,,!
말씀하신 걸 생각 해 봤을 때 ing 형태로 작성하게 되면 동사가 아니기 때문에 가시성이 떨어지는 문제가 있을 수 있을 것 같습니다.!
혹시 어떻게 생각하시는지 여쭤봐도 될까요~?
LocalizedError 프로토콜을 채택하셨군요 👏 해당 프로토콜은 무엇을 위해서 채택하셨을까요?

public var errorDescription: String? 를 정의해서 error.localizedDescription 으로 에러 문구 출력을 할 수 있게 하기 위해 채택하였습니다!

이전에는 그냥 Error 타입을 채택해, printError 함수를 구현하고호출하는 do - catch 부분에서 InputError 타입일 경우에 printError() 를 호출하게 분기 처리를 따로 해줘야 했는데, 더 나은 방법이 없을까 알아보다 알게 되었습니다 :)

+질문) InputError 타입을 정의할 때 에러 메시지를 String rawValue 로 넣어줬는데,다른 예시를 찾아보다 보니 errorDescription 을 구현할 때 switch self 를 통해서 각 케이스마다 에러 메시지를 return 하게 구현한 방식도 많은 걸 발견했습니다.두 가지 중에 어떤 것을 채택하느냐는 error 메시지를 출력하는 경우 외에 rawValue 를 따로 사용할 일이 있느냐, 없느냐 정도로 생각하는 것이 맞을까요? 의견이 궁금합니다 :)

자답) 공부하다가,에러의 경우 서버 응답 코드와 rawValue를 매칭해서 사용하곤 하기 때문에 rawValue에 출력 문구를 사용하는건 지양하는게 좋다는 의견을 알게 되었습니다!
🚨 현재 split(separator:) 메서드를 호출할 때 넘겨주는 매개변수가 잘못되어서 프로그램이 실제로 동작하고 있지 않은 것 같습니다. 확인부탁드려요 🙏🏻

split(separator:) 에 공백이 포함된 “ / “ 를 넘겼는데, 빌드 타겟을 13.0 미만으로 바꾸니 해당 현상이 재현되었습니다.
separator 파라미터에 두 글자 이상을 넘길 때에 생기는 문제인데 기본 split 메서드는 한 글자만 허용했었고,두 글자 이상 허용하는 메서드는 macOS 13.0 이후에 추가되었다는 것을 알게 되었습니다.split 대신 components 를 사용하기로 했고, 두 메서드의 차이에 대해서 학습하였습니다 :D
Bool 타입이 반환형일때는is~, has~ prefix가 붙는게 더 좋아보입니다!
해당 함수를 따로 구현하지 않고 splitBySlash함수 내부에 중첩한 이유도 궁금합니다 🙋‍♂️

splitBySlash -> parse
checkFormat -> isValidFormat으로 함수명을 수정하였습니다.
중첩 함수로 구현한 이유는, 파싱 이라는 과정 안에 올바른 포맷인지 검증하는 과정이 포함되어 있다고 생각했고해당 검증함수는 오직 파싱 함수만을 위해 사용되기에 중첩 함수로 구현하는 것이 좋지 않을까? 라는 생각이 들었습니다.
그럼에도 함수를 밖으로 따로 분리해야 한다면 isValidFormatToParse 같은 식으로 함수이름에 역할을 분명히 해줘야 할 것 같다는 생각이 듭니다.
밖으로 따로 분리하는 것의 기준을 재사용성이 있는지와 가시성을 해치는지 아닌지를 생각했는데.. 혹시 그 외의 기준이 있을까요?결론적으로 따로 분리하는 것이 더 나은 코드일까요~?
만약 여기서 0번째가 없다면 해당 프로그램은 어떻게 될까요?
배열에서 index를 사용해서 직접 접근하는 것은 위험합니다.
hint: [[배열에 구현 되어 있는 메서드](https://developer.apple.com/documentation/swift/array)](https://developer.apple.com/documentation/swift/array) 들 중에서 안전하게 접근할 수 있는 것이 무엇인지 찾아보면 어떨까요?

Extension을 추가하고, 옵셔널 바인딩 통해 값을 사용하도록 수정해봤습니다.
extension Array {
    subscript(safe index: Int) -> Element? {
        return indices ~= index ? self[index] : nil
    }
}
struct와 enum을 사용하신 기준이 궁금합니다 🙋‍♂️

저장 속성을 갖지 않고 static func 들만 갖고 있는 타입은 굳이 인스턴스화를 하지 않게끔 enum 으로 구현하였습니다.해당 PhoneBookManager 를 struct 로 구현한 이유는 차후 연락처 모델의 데이터를 저장 속성으로 갖게 될 것 같아 구조체로 구현하였습니다.

Use structures by default.
Use classes when you need Objective-C interoperability.
Use classes when you need to control the identity of the data you’re modeling.
Use structures along with protocols to adopt behavior by sharing implementations.
구조체는 mutating 을 매번 함으로서 매번 값을 복사하게 되므로 final class 로 구현해야 하나 고민이 있는데, 퍼포먼스 차이를 찾아본 결과 큰 차이가 없고 오히려 struct 가 빠를 때도 있다는 의견이 있어 고민이 됩니다.공식 문서의 해당 내용을 바탕으로는 struct 가 낫겠다고 생각했습니다!

+) 그리고 이번에 수정사항을 반영하며 느낀 것인데, 커밋은 수정사항 하나마다 따로 커밋하는 것이 좋겠다는 생각이 들었습니다.
다음 스텝 부터는 해당 부분을 지키도록 노력해보겠습니다!

2022-12-27 08:01 UTC, qwerty3345 commented
안녕하세요 제이크! @jryoun1
정성스럽게 써주신 리뷰 덕분에 많은 부분을 고민 해 보고, 공부해볼 수 있게 되었습니다 🙂
수정 사항 반영 하였고, 질문들은 코멘트에 다시 코멘트 남겨 드렸습니다!
그리고 코멘트에 질문드린 사항들을 따로 정리해서 보내드립니다 :) (코멘트와 동일합니다)

1. static을 써보셨군요 👏 언제 static func를 사용할까요?
    - 인스턴스를 생성하지 않고, 함수를 사용할 수 있게 하는 키워드가 static func 인데해당 타입 메서드의 경우엔 저장 속성에 대한 접근을 필요로 하지 않고,단순히 파라미터 3개를 받아 유저에게 콘솔창으로 출력 해 주는 `순수함수`이기 때문에 static func 로 구현하였습니다 :)
    - +) 다음 스텝에 가게 되어서, 연락처 모델을 구조체로 구현한다면저장 속성인 name, age, phoneNumber 을 String 문자열로 적절히 변환해주는 description 과 같은 계산 속성으로 구현하는 것이 좋을 것 같다는 생각을 했습니다.
2. 함수명은 동사로 시작합니다! [[문서](https://www.swift.org/documentation/api-design-guidelines/#naming)](https://www.swift.org/documentation/api-design-guidelines/#naming)에서 예시들을 참고해보면 좋을 것 같아요 🙏🏻
    
    ```swift
    extension String {
        func removingWhiteSpaces() -> String {
    ```
    
    - Swift API Guideline - naming 파트의 "Name functions and methods according to their side-effects" 에서 `sort()`, `sorted()` 의 차이에 대해 공부하다가 non-mutating 함수이기 때문에 ed/ing 형태로 명명하는 것이 나을 것 같아 수정하였었는데요,,!
    말씀하신 걸 생각 해 봤을 때 ing 형태로 작성하게 되면 동사가 아니기 때문에 가시성이 떨어지는 문제가 있을 수 있을 것 같습니다.! 
    혹시 어떻게 생각하시는지 여쭤봐도 될까요~?
3. LocalizedError 프로토콜을 채택하셨군요 👏 해당 프로토콜은 무엇을 위해서 채택하셨을까요?
    - `public var errorDescription: String?` 를 정의해서 `error.localizedDescription` 으로 에러 문구 출력을 할 수 있게 하기 위해 채택하였습니다!
    - 이전에는 그냥 Error 타입을 채택해, `printError` 함수를 구현하고호출하는 do - catch 부분에서 InputError 타입일 경우에 printError() 를 호출하게 분기 처리를 따로 해줘야 했는데, 더 나은 방법이 없을까 알아보다 알게 되었습니다 :)
    - +질문) `InputError` 타입을 정의할 때 에러 메시지를 `String rawValue` 로 넣어줬는데,다른 예시를 찾아보다 보니 `errorDescription` 을 구현할 때 `switch self` 를 통해서 각 케이스마다 에러 메시지를 return 하게 구현한 방식도 많은 걸 발견했습니다.두 가지 중에 어떤 것을 채택하느냐는 error 메시지를 출력하는 경우 외에 rawValue 를 따로 사용할 일이 있느냐, 없느냐 정도로 생각하는 것이 맞을까요? 의견이 궁금합니다 :)
        
        > 자답) 공부하다가,에러의 경우 서버 응답 코드와 rawValue를 매칭해서 사용하곤 하기 때문에 rawValue에 출력 문구를 사용하는건 지양하는게 좋다는 의견을 알게 되었습니다!
        > 
4. 🚨 현재 split(separator:) 메서드를 호출할 때 넘겨주는 매개변수가 잘못되어서 프로그램이 실제로 동작하고 있지 않은 것 같습니다. 확인부탁드려요 🙏🏻
    - `split(separator:)` 에 공백이 포함된 “ / “ 를 넘겼는데, 빌드 타겟을 13.0 미만으로 바꾸니 해당 현상이 재현되었습니다.
    - `separator` 파라미터에 두 글자 이상을 넘길 때에 생기는 문제인데 기본 `split` 메서드는 한 글자만 허용했었고,두 글자 이상 허용하는 메서드는 macOS 13.0 이후에 추가되었다는 것을 알게 되었습니다.`split` 대신 `components` 를 사용하기로 했고, 두 메서드의 차이에 대해서 학습하였습니다 :D
5. Bool 타입이 반환형일때는`is~`, `has~` prefix가 붙는게 더 좋아보입니다!
해당 함수를 따로 구현하지 않고 splitBySlash함수 내부에 중첩한 이유도 궁금합니다 🙋‍♂️
    - `splitBySlash` -> `parse`   
    `checkFormat` -> `isValidFormat`으로 함수명을 수정하였습니다.
    - 중첩 함수로 구현한 이유는, 파싱 이라는 과정 안에 올바른 포맷인지 검증하는 과정이 포함되어 있다고 생각했고해당 검증함수는 오직 파싱 함수만을 위해 사용되기에 중첩 함수로 구현하는 것이 좋지 않을까? 라는 생각이 들었습니다.
    - 그럼에도 함수를 밖으로 따로 분리해야 한다면 isValidFormatToParse 같은 식으로 함수이름에 역할을 분명히 해줘야 할 것 같다는 생각이 듭니다.
    - 밖으로 따로 분리하는 것의 기준을 재사용성이 있는지와 가시성을 해치는지 아닌지를 생각했는데.. 혹시 그 외의 기준이 있을까요?결론적으로 따로 분리하는 것이 더 나은 코드일까요~?
6. 만약 여기서 0번째가 없다면 해당 프로그램은 어떻게 될까요?
배열에서 index를 사용해서 직접 접근하는 것은 위험합니다.
hint: [[배열에 구현 되어 있는 메서드](https://developer.apple.com/documentation/swift/array)](https://developer.apple.com/documentation/swift/array) 들 중에서 안전하게 접근할 수 있는 것이 무엇인지 찾아보면 어떨까요?
    - `Extension`을 추가하고, 옵셔널 바인딩 통해 값을 사용하도록 수정해봤습니다.
    
    ```swift
    extension Array {
        subscript(safe index: Int) -> Element? {
            return indices ~= index ? self[index] : nil
        }
    }
    ```
    
7. struct와 enum을 사용하신 기준이 궁금합니다 🙋‍♂️
    - 저장 속성을 갖지 않고 `static func` 들만 갖고 있는 타입은 굳이 인스턴스화를 하지 않게끔 `enum` 으로 구현하였습니다.해당 `PhoneBookManager` 를 `struct` 로 구현한 이유는 차후 연락처 모델의 데이터를 저장 속성으로 갖게 될 것 같아 구조체로 구현하였습니다.
        
        > Use structures by default.
        Use classes when you need Objective-C interoperability.
        Use classes when you need to control the identity of the data you’re modeling.
        Use structures along with protocols to adopt behavior by sharing implementations.
        > 
    - 구조체는 `mutating` 을 매번 함으로서 매번 값을 복사하게 되므로 `final class` 로 구현해야 하나 고민이 있는데, 퍼포먼스 차이를 찾아본 결과 큰 차이가 없고 오히려 struct 가 빠를 때도 있다는 의견이 있어 고민이 됩니다.공식 문서의 해당 내용을 바탕으로는 struct 가 낫겠다고 생각했습니다!

+) 그리고 이번에 수정사항을 반영하며 느낀 것인데, 커밋은 수정사항 하나마다 따로 커밋하는 것이 좋겠다는 생각이 들었습니다.
다음 스텝 부터는 해당 부분을 지키도록 노력해보겠습니다!

2022-12-28 00:48 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/PhoneBookManager.swift
> +struct PhoneBookManager {
좋네요 공부를 많이 하셨군요! 
나중에 시간이 된다면 [WWDC16 - Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/)도 한 번 보시면 class, struct에 대해서 도움이 될 것 같네요! 
(프로젝트 중간이 아닌 이번 프로젝트 끝나고나 주말이나 시간이 남을 때 보는걸 추천드려요!)

2022-12-28 00:53 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        return array[0].removingWhiteSpaces()
안전하게 배열 index에 접근할 수 있도록 개선이 되었네요 ㅎㅎ

2022-12-28 00:57 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/InputManager.swift
> +        func checkFormat(for inputArray: [String]) -> Bool {
앗 제가 여쭤본 것은 진짜 이유가 궁금해서 여쭤본 것이라서 꼭 밖으로 빼야한다거나 그런걸 의도하고 질문드린 것은 아닙니다 ㅎㅎ 
말씀하신 것처럼 함수를 분리하는 이유는 재사용성이라는 측면과 하나의 함수가 너무 많은 역할을 하고 있지 않은지에 따라서 분리를 할 수 있을 것 같네요. 
검증이라는 함수가 내부에서만 쓰인다고 한다면, private 함수로 생성하여 외부에서는 접근을 제한하고 내부에서는 parse 함수가 진짜 하나의 역할만 하게 작게 분리해서 사용할 수도 있을 것 같아요 ㅎㅎ
 
코드에 정답은 없으니 두 분이서 논의해보시고 더 좋은 걸로 진행하시면 될 것 같아요 🙏🏻

2022-12-28 01:00 UTC, jryoun1 commented on PhoneBookManager/PhoneBookManager/Extensions.swift
> +    func removingWhiteSpaces() -> String {
> sort(), sorted() 의 차이에 대해 공부하다가 non-mutating 함수이기 때문에 ed/ing 형태로 명명하는 것이 나을 것 같아 수정하였었는데요,,!

오히려 제가 놓친것 같네요! ㅎㅎ non-mutating이라서 말씀하신대로 ing로 네이밍해도 좋아보입니다 👍🏻👏

2022-12-28 01:02 UTC, jryoun1 approved these changes
고생하셨습니다! 
정말 잘 수정 및 의견들을 제시해주셨네요 ㅎㅎ 

앗 질문들과 답변들을 모아서 코멘트로 너무 잘 정리해주셨는데, 어짜피 코멘트별로 다시 확인을 해서 해당 부분은 저를 위해서 따로 안 모아주셔도 괜찮을 것 같습니다 🙏🏻

2022-12-28 01:02 UTC, merged