연락처관리 [STEP 1] Jenna, JoJo
tasty-code/ios-contact-manager pull request #4
Opened 2022-12-23 07:00 UTC by ueunli

안녕하세요 @corykim0829 🥳
저희

## 그라운드 룰
- 네이밍 규칙 준수
- 커밋
   - 커밋메시지 양식 통일
   - 기능단위별 커밋
- 짝코딩 진행 방식
   - 4커밋마다 git merge-push-pull

## 구현사항
//- [ ] 입력값 받기
//- [ ] 입력값 검증
- [ ] 연락처 정보 추가
   - [ ] 이름정보 가공) 사용자 입력값에서 띄어쓰기 제거
   - [ ] 나이정보 검증) 3자리 이하 숫자인지
   - [ ] 연락처정보 검증) `-`가 2개인지, 숫자가 9자리 이상인지

## 구현 과정
> ### 파일 목록
> - Profile: 연락처 데이터 타입 정의
> - InputManager: 입력값 검증
> - ContactManageSystem: 입력값을 통한 데이터 인스턴스 생성
> - ValidInputError: 에러 정의

### Struct vs Class
둘 차이점 조사, 뭐가 적절할지 고민했으나 별다른 이유 없어 권장하는 대로 구조체 하기로 

### 에러처리
- 

### 입력값 검증

2022-12-24 05:18 UTC, corykim0829 requested changes
수고 많으셨어요 Jojo, Jenna !! 👏👏👏👏
첫번째 PR을 축하드립니다! 🎉

전반적으로 코드가 깔끔하고, 고차함수를 잘 사용하신 점이 눈에 띄네요! 😎
`InputManager`를 만들어서 일을 분리시킨 점도 매우 좋았습니다!

제가 커멘트 남겨드린 부분 우선으로 수정하시고, 시간 여유가 있다면 아래 언급한 내용을 진행하면 좋을 것 같습니다!

---

고차함수 사용은 매우 좋으나, 이 코드를 작성하지 않은 사람이 봤을 때에는 헷갈릴 수 있으니 항상 가독성을 잘 고려해야합니다!
제가 커멘트 드렸던 개행 처리로 가독성을 높이면 좋을 것 같아요!

커멘트로도 남겨드렸지만, `Index out of range` 에러는 놓치기 쉬운 부분이기 때문에 유의하시면 좋을 것 같아요!

또한 시간의 여유가 있다면 `InputManager`처럼, `OutputManager`를 만들어서 출력을 처리할 객체를 만들어보면 좋을 것 같습니다 :)

두분 정말 수고 많으셨고 🌟메리크리스마스🌟입니다!! 🎄🎄🎄🎄

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +        let splitInput = input.components(separatedBy: "/").map { $0.replacingOccurrences(of: " ", with: "") }
map으로 공백 제거 처리를 잘하셨네요!
여기 map `{` 이후에도 개행처리를 해서 더 가독성을 높여주면 좋을 것 같아요!

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +        return [splitInput[0], splitInput[1], splitInput[2]]
지금은 예시로 주어진 입력에서는 괜찮지만, 이렇게 배열의 특정 index에 접근할 때에는 `Index out of range` 에러를 항상 고려해야합니다. 참고만하세요!

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +    func checkUserInput(name: String, age: String, tel: String) throws -> (String, String, String) {
해당 함수명만 보면, 검증만 하는 것 같은 느낌이 드는데, 3가지 값을 반환하고 있네요! 이해하기 더 좋은 함수명으로 수정하면 좋을 것 같아요!

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +        guard (tel.filter { $0 == "-" }).count == 2 else { throw ValidInputError.notValidTel }
2 매직넘버도 상수로 만들면 좋을 것 같네요!

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +    func checkUserInput(name: String, age: String, tel: String) throws -> (String, String, String) {
또한 이 함수 내부에서 사용한 guard문도 개행으로 정리해주세요! 😊

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/Profile.swift
> +    var name: String
var와 let 중에 어떤 걸 사용하면 더 좋은지 고민해보면 좋을 것 같아요!

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/InputManager.swift
> +    func parseUserInput() throws -> [String] {
throw를 사용하여 함수를 잘 구현하셨네요! 👍

2022-12-24 05:18 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +            contactList.updateValue(Profile(name: name, age: age, tel: tel), forKey: name)
Profile 인스턴스를 한줄에 먼저 생성해서 파라미터로 넣어주는게 더 가독성에 좋습니다! 😊

2022-12-26 07:24 UTC, CODEMASTERJO commented
안녕하세요 @corykim0829 🙌
황금같은 주말시간에 PR 확인해주셔서 감사합니다!
답변 주신 내용을 최대한 반영해보려고 했는데 잘 되었는지 모르겠네요...

## 고민과 해결
`checkUserInput naming` 답변 주신것을 보고 처음에는 제대로 이해하지 못했습니다. 검증 후 검증완료된 리턴값을 반환하는 단계를 검증, 반환 2단계로 보아야하는가? 두 가지의 기능을 포함한 적절한 Naming이 있는가? 등으로 고민하면서 수정방향을 잡지 못했습니다.
그러던 중 버디 `Finnn`에게 질문 하였고, 체크함수를 리턴형이 없거나 Bool타입을 리턴하는 함수로 리팩토링 해보는것이 어떻냐는 조언을 해주어 이를 기반으로 수정해보았습니다.

## 피드백 관련 구현사항

- [x]  **Profile Struct 생성자 생략 - Struct는 기본 `생성자`가 생략되므로 삭제해도 된다.**
  - 전주에 Class vs Struct를 배우면서 멤버와이즈 이니셜라이저에 대해 배웠는데 프로젝트에서는 놓쳤네요😭 삭제했습니다.

- [x]  **ValidInputError → InputError - `Naming`**
**notValidAge, Name, Tel → inValid - `Naming`**
  - `Naming`과 `영단어`의 중요성을 느껴져요. 공식문서를 매번 읽어보지만 계속 읽어도 막상 `Naming`할때 잘 떠오르지 않네요

- [x]  **`contactManage`프로퍼티명 통일**
  - 구조체(`ContactManageSystem`)명과 통일하였습니다.

- [x]  **guard - else문 - else 뒤에 추가 작업이 있다면 `줄바꿈` 을 해주자
map 이후 `개행처리`**
  - 다른 코드에서 고차함수나 guard-else문을 한 줄로 작성한 내용을 본적이 있어서 이전 코드도 한줄로 작성하였는데 혹시 Cory만의 개행처리의 기준이나 Convenience가 있을까요? 어떤 기준으로 개행처리를 해야할지 어렵네요

- [x]  **`Index out of range`**
  - 요구사항으로만 코드를 구현하고자 해서 해당 내용을 놓쳤던것같습니다. index out of range를 간단하게라도 커버할 수 있는 방법을 고민하다가 사용자 입력을 3부분으로 나누어 받을 수 있는지 검증하는 guard문을 하나 더 만들었습니다. (매직넘버도 하나 추가했습니다!)

- [x]  **checkUserInput `Naming`**
  - 검증과 할당을 모두 포함하는 영단어를 찾기 또는 함수를 기능별로 구분 둘 중을 고민하던 중 name, age, tel의 return값을 이중으로 처리하고 있었다는 것을 깨닫고 checkUserInput을 return값이 없는 함수로 수정 하였습니다.

- [x]  **2 `매직넘버`**
  - 이전에 매직넘버를 사용하여 함수 처리하는 것을 보았지만 매직넘버라는 정의는 이번에 처음 알았네요! 
  - 하이픈의 개수(2)를 `hyphenCount`라는 상수에 담아 매직넘버로 만들었습니다. 
/로 구분되는 사용자 입력이 3개가 되도록 제한하는 guard문에서도 `splitInputCount`라는 매직넘버를 사용하도록 했습니다.

- [x]  **`var` vs `let`**
  - 이름은 불변한다고 생각하며 차후에 검색기능이 추가되는 것을 보고 이름을 key값으로 가져가고자 `let`으로 정의하였고, 나머지 나이와 연락처는 변할 수 있다고 생각하여 `var`로 정의하였습니다.

- [x]  **Profile `인스턴스 먼저 생성 후 파라미터` 입력**
  - 기존 인스턴스 생성과 update를 동시에 진행하고 있던 절차를 2개로 구분하여 생성된 인스턴스를 상수에 할당한 후 updaterValue에 매개변수로 해당 상수를 넣었습니다.

## 피드백 관련 미구현사항
- [ ]  **`OutputManager`추가**
  - 팀원과 같이 얘기해본 결과 다음 STEP 기능 추가와 함께 `OutputManager`를 분리해보려고 합니다.

## 추가 구현사항
- [x]  **`parseUserInput` 함수 return값**
  - 동일한 절차를 중복 수행하고 있어서 parseUserInput()함수의 반환형을 `[splitInput[0], splitInput[1], splitInput[2]]` → `splitInput` 으로 바꿨습니다.

2022-12-26 09:40 UTC, corykim0829 approved these changes
수고많으셨습니다! 👏👏👏👏
첫번째 PR 머지 축하드립니다 :) 🔥

남겨드린 커멘트는 다음 스텝 진행하면서, 개선해보면 좋을 것 같아요!

2022-12-26 09:40 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/ContactManageSystem.swift
> +    var contactList = [String: Profile]()
List는 Array느낌이 강한 것 같아서, 네이밍을 조금 더 고려해보면 좋을 것 같아요!

2022-12-26 09:40 UTC, corykim0829 commented on ios-cantact-manager/ios-cantact-manager/Profile.swift
> +    var tel: String
보통 이런 작은 struct 모델 객체에서는 let으로 쓰는게 좋습니다! let으로 통일하면 좋을 것 같아요 :)

2022-12-26 09:40 UTC, merged