연락처관리 [STEP 1] sunny, is
tasty-code/ios-contact-manager pull request #5
Opened 2022-12-23 07:55 UTC by vanism2091

- [Summary](#summary)
- [작업 목록](#작업-목록)
- [작업 목록 구현](#작업-목록-구현)
  - [String Literal 작성](#string-literal-작성)
  - [입력/출력 구현](#입력출력-구현)
  - [에러 정의](#에러-정의)
  - [입력 검증](#입력-검증)
  - [‘/‘ 검증](#-검증)
  - [이름/나이/연락처 검증](#이름나이연락처-검증)
- [🤔특별히 궁금한 점🤔](#특별히-궁금한-점)
  - [1. 정규식 검증 방식](#1-정규식-검증-방식)
  - [2. issue 작성](#2-issue-작성)
  - [3. Commit 단위](#3-commit-단위)
  - [4. Naming 고민](#4-naming-고민)

안녕하세요 vivi! Is와 Sunny 입니다!😆😀 
Step1 의 조건 사항에 맞춰 최대한 열심히 짝 프로그래밍을 해 보았습니다. 처음 해보는 짝 프로그래밍이라 어색하기도 했지만, 서로 다른 구현 방식을 보면서 신기한 것도 많았던 경험이었어요!

밑에 보시면 🤔특별히 궁금한 점🤔 을 적어놓았습니다! 저희가 인터넷으로 검색도 하고, 나름대로 연구도 하면서 구현을 해 보았지만 아직 저희만의 기준이 잡히지 않아 생기는 고민들을 적었습니다. 또한 서로 구현 방법이 다를 때, 어떤 코드가 효율적인지 vivi의 의견을 듣고 싶어 적어보았습니다.☺️

저희 코드를 리뷰해주셔서 감사해요! 주신 리뷰는 열심히 고민하고 공부하겠습니다!!!

## Summary

이름, 나이, 연락처 사용자의 입력을 받아 올바른 형식으로 입력했다면 입력한 내용을 출력해주고 그렇지 않다면 오류 내용을 출력해주는 기능을 구현했습니다.

## 작업 목록

- [x] String Literal
- [x] 입력 구현
- [x] 출력 구현
- [x] 에러 정의
- [x] 검증 시작
  - [x] ‘/’
  - [x] 이름
  - [x] 나이
  - [x] 연락처

## 작업 목록 구현
### String Literal 작성
StringLiteral.swift
- app에서 사용하는 모든 String 을 한 파일로 구현 

### 입력/출력 구현
IOManager.swift
- 출력의 type을 enum으로 생성
- getInput() : 사용자에게 입력을 받아 nil일 경우 emptyInput error 처리
- sendOutput() : PrintType에 따라 출력 case 정의

### 에러 정의
Error.swift
- Error타입을 enum으로 생성
- LocalizedError를 채택해 errorDescription 구현 : IOError 타입 별 error message 다르게 설정

### 입력 검증
Extension.swift, ContactManager.swift, UserInfo.swift
- 정규식으로 사용자가 입력한 정보를 검증하는 방식에 대해 고민이 많았습니다. 더 자세한 내용은 아래 🤔특별히 궁금한 점🤔을 참고해주세요!

### ‘/‘ 검증
- ContactManager.swift 의 parse() 를 통해 ‘/‘을 검증하였습니다. 저희는 기존 기준을 더 명확히 하기 위해 추가적인 제한을 더 추가했습니다.
    - “이름 / 나이 / 전화번호” : / 기준으로 앞,뒤 space
    - “이름/나이/전화번호” : / 기준으로 앞,뒤 모두 space X
    - 이 두가지의 경우에만 ‘/‘ 검증을 통과하도록 했습니다. 
    - 예를들어 “이름/ 나이/ 전화번호” 이런 경우, 통과하지 못하도록 구현했습니다. 

### 이름/나이/연락처 검증
- UserInfoParams 로 이름, 핸드폰번호의 정규식, 에러를 enum으로 정의했습니다. 
- UserInfo 타입을 생성해 정규식을 통해 각 속성을 검사하고, 검사에 통과한 정보만이 UserInfo 인스턴스로 생성 가능하도록 구현했습니다.

## 실행 결과
- 올바른 입력
![_](https://user-images.githubusercontent.com/107124308/209295250-ecb4c07f-7aed-41b9-86d6-461656394ace.png)
- 입력 형식 오류
![형식오류1](https://user-images.githubusercontent.com/107124308/209295157-4fc93663-1cff-480b-91ad-e222552970b4.png)
![형식오류2](https://user-images.githubusercontent.com/107124308/209295259-4c84f6f2-952d-44b9-a6fa-f9d43f64093f.png)
- 이름 오류
![_](https://user-images.githubusercontent.com/107124308/209295187-6748019b-feb1-4c32-9433-aa4a4acff71e.png)
- 나이 오류
![_](https://user-images.githubusercontent.com/107124308/209295196-7485b4f1-9219-4e51-8da0-1a34835f980d.png)
- 연락처 오류
![_](https://user-images.githubusercontent.com/107124308/209295217-a5a1c2a6-1039-48b0-8bc7-0319f0196822.png)

## 🤔특별히 궁금한 점🤔

### 1. 정규식 검증 방식
1. 구현하다가 정규식 검증 방식에 대해 is와 sunny가 다른 의견을 가진 부분이 있었습니다. 둘 다 무엇이 좋은지 알 수 없어서 이에 대한 vivi의 생각이 궁금해요!

  - 문제 상황:
    - 정규식에 맞추어 입력을 검증해야 한다.
    - 이름, 나이, 연락처는 각각 다른 정규식으로 검증해야 한다.
    - UserInfo에서 init 시 vaildity 검증 후 통과하지 않으면 error를 던진다
    - extension String으로 정규식을 받고 문자열을 검증하는 메소드를 확장한다
      - extension 방식에 대한 고민!
  - 공통 코드

    - main.swift - test code

    ````swift
    let goodName = "Su  n ny "
    let badName = "sssss  ss00"

    let t1 = try? UserInfo(name: goodName)
    do {
        let t2 = try UserInfo(name: badName)
    } catch {
        print(error.localizedDescription)
    }
    - UserInfo.swift
    ```swift

    enum UserInfoParams {
        case name, age, phone

        var regex: String {
            switch self {
            case .name:
                return "^[A-Za-z ]+$"
            case .age:
                return "age regex"
            case .phone:
                return "phone regex"
            }
        }

        var error: IOError {
            switch self {
            case .name:
                return IOError.nameError
            case .age:
                return IOError.ageError
            case .phone:
                return IOError.phoneError
            }
        }
    }
    ````

  - sunny 생각
    - 정규식을 String으로 주기 때문에, String에 extension으로 정규식 검증하는 함수를 만들었습니다.
    - 정규식 검증 함수는 init 안에 넣어 정규식에 맞는 input만 받아 인스턴스를 생성할 수 있도록 했습니다.
    - Extension.swift
    ```swift
    extension String {
        func getInfoAfter(type: UserInfoParams) throws -> String {
            guard let info = self.range(of: type.regex, options: .regularExpression) else {
                throw type.error
            }
            return self+"good"
        }
    }
    ```
    - UserInfo.swift
    ```swift
    struct UserInfo {
        let name: String
        let age: String? = nil
        let phone: String? = nil

        init(name: String) throws {
            do {
                self.name = try name.getInfoAfter(type: .name)
                print(self.name)
            } catch {
                throw error
            }
        }
    }
    ```
  - is 생각
    - String은 프로젝트 내 모든 코드에서 쓸 수 있으므로 extension String 시, 특정한?specific한 custom type이 연관되지 않는 편이 좋은 것 같았습니다 🙂
    - Extension.swift
    ```swift
    extension String {
        static func ~= (_ lhs: String, _ rhs: String) -> Bool {
            return lhs.range(of: rhs, options: .regularExpression, range: nil, locale: nil) != nil
        }
    }
    ```
    - UserInfo.swift - init
    ```swift
    struct UserInfo {
        init(name: String, age: String, phone: String) throws {
                guard Self.checkValidity(of: name, type: .name) else {
                        throw IOError.nameError
                }
                // ...
        }

        static func checkValidity(of item: String, type: UserInfoParams) -> Bool {
                return item ~= type.regex
            }
        }
    }
    ```

### 2. issue 작성
이슈를 처음 써봐서, issue 작성 단위가 적절한지 궁금해요! 
![issue](https://user-images.githubusercontent.com/107124308/209293695-571327f0-e3fc-4a40-bd3c-937fd0868887.png)

### 3. Commit 단위
작성한 이슈를 바탕으로 큰 커밋 단위를 세우고, 짝프로그래밍을 진행하며 기능 구현에 따라 커밋이 세부적으로 추가되었어요. 
- 어떤 커밋은 2줄만 바꿨지만 하나의 기능이라 커밋한 [경우](https://github.com/SunnnySong/ios-cantact-manager/commit/dece151d8abda8055d03f8942c59462bf834012d)도 있었고,
- 어떤 커밋은 여러 기능이 바뀐 [경우](https://github.com/SunnnySong/ios-cantact-manager/commit/d51f9036b94e7e8705391a244bdfdabc85af210a)도 있었어요.

적절한 커밋의 단위가 궁금해요! 아무리 짧은 라인이 바뀌었다 하더라도 기능별로 커밋하는게 좋을까요?

### 4. Naming 고민
좋은 네이밍이 어떤건지 아직 감이 잡히지는 않는데 우리의 네이밍이 좋지 않은 것 같다는 느낌은 진하게 들어요😭
코드를 보며 흐음..🤔싶은 곳이나 제안하고 싶은 네이밍이 있으면 많이 많이 알려주세요!!

2022-12-25 16:01 UTC, YebinKim requested changes
이즈, 써니 안녕하세요~
Step1 진행 고생 많으셨어요 😆
작업 목록부터 실행 결과, 질문까지 꼼꼼하게 남겨주셔서 코드를 읽는데 도움됐습니다!

또한, 접근 제어 및 함수 인자 활용, Optional의 활용과 바인딩, 구조체와 클래스의 적절한 활용, 에러 처리까지 굉장히 많은 신경을 쓴 코드임이 느껴졌습니다! 👍👍

리뷰 코멘트 확인 전 아래 내용 확인 부탁드리며, 질문 사항은 밑줄선 아래에서 일괄 답변드리도록 할게요~

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. 정규식 검증 방식
sunny와 is의 생각이 모두 일리 있다고 생각해요~
둘 중 어느 방법이 적절한가 이전에 `String` 이 특정 파일에서만 접근될 수 있도록 Access Control 과 extension 을 결합하면 프로젝트 내 모든 코드에서 접근 가능하지 않게 사용이 가능하다는 점을 참고로 말씀드리며,
두 분이 충분히 논의한 결과로 작성된 현재의 방식이 좋다고 생각합니다! 😄🙌


### 2. issue 작성
현재는 프로젝트의 단위가 크지 않아서 단위에 대해 얘기하기 어렵지만,
프로젝트 크기 대비 각 이슈에서 많게는 3개 적게는 1개 커밋이 올라간 현재가 적절하다는 생각이 들어요!

또한, 이슈와는 별개로 PR을 생성했을 때는 상호 간의 리뷰의 편리함을 위해 Line Changes 를 200줄 내외로 작성하는 것을 선호합니다! (물론 현재 우리와 같이 Step 별 리뷰를 진행할 때는 해당하지 않는 내용입니다 😊)


### 3. Commit 단위
저는 커밋을 남기는 이유가 개발 작업을 `빌드가 가능하며 기능 단위로 나눌 수 있는 상태` 단위로(나누기 위함이고, 여러 개발자가 히스토리를 파악하기 위함이라고 생각했을 때
**한 커밋에서는 해당 코멘트에 작성한 내용**만 포함되도록 작성하는 것이 좋다고 생각해요!
또한, 가능하다면 **한 기능에 대한 하나의 작업 내용만 포함**되는 것이 좋다고 생각해서 `아무리 짧은 라인이 바뀌었다 하더라도 기능별로 커밋` 하는 쪽에 좀 더 공감하는데요.
하지만 개발 작업은 항상 절대적인 정답 보다는 상황에 따라 적절한 방법을 따르는 게 최선이기 때문에 절대적으로 기능별 커밋만을 따르는 것은 어렵다고 생각해요 😄

그리고 한 커밋에서 작업 내용이 너무 많아지지 않게 유의하는 것도 필요하다고 생각합니다~!!


### 4. Naming 고민
코드를 읽으며 더욱 신경써서 봤습니다! 라인별 코멘트 확인 부탁드려요~

---

이번 스텝에서의 핵심 경험은 아래와 같았는데요.
<img width="353" alt="step1 핵심 경험" src="https://user-images.githubusercontent.com/38066039/209474725-fa59611e-41aa-40a0-af71-9cc4bf1e5687.png">

`Swift API Design Guide에 따른 이름짓기` 와 관련해 코멘트가 몇 개 있어 Request Changes 로 남겨두었습니다.
리뷰 코멘트와 관련해 궁금한 점이 있다면 편하게 물어봐주세요!! ☺️🙌

2022-12-26 04:08 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/UserInfo.swift
> +    case name, phone
```swift
// IOManager.swift
enum PrintType {
    case menu
    case infomation
    case error
}

// Error.swift
enum IOError: Error {
    case emptyInput
    case nameError
    case ageError
    case phoneError
    case inputFormatError
}

// UserInfo.swift
enum UserInfoParams {
    case name, phone
		//...
}
```
PrintType과 IOError는 한 줄로 나열하면 가독성이 좋지 않은 반면, UserInfoParams는 name, phone밖에 없으므로 한 줄로 나열해도 가독성이 좋아서 한 줄로 나열했습니다! 
코드의 일관성을 위해 개행을 하는게 좋을까요?

2022-12-27 07:26 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/UserInfo.swift
> +struct UserInfo {
- InfoInput은 사용자의 input의 형태와 의미에 관한 tuple이고(아직 타입별 검증 전인, ‘/’ 나누어진 rawInput), UserInfo는 초기화 시 각 타입이 적절히 입력되었는지 검증하기 위해 만든 struct예요! 
- 그래서 InfoInput은 모든 property가 String type인 반면, UserInfo는 009처럼 입력된 나이를 9로 출력하기 위해 age property의 type을 Int 로 설정했어요. 
- 결론은, 각각 서로 다른 역할을 하기에
    - InfoInput: input에 대한 의미를 분명히 함 
    - UserInfo: input의 세부 타입인 name, age, phone의 적절성을 검증함
- 두 개로 나눠서 만들었습니다!

2022-12-27 07:29 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +    static let shared = ContactManager()
- 이유
  - 제가 프로젝트를 해석한 바, ContactManager의 역할은 유저가 입력한 Contact(UserInfo)들을 관리하는 것입니다.
  -  ContactManager에게 Contacts라는 ‘상태’가 있(을예정이)기에 ContactManager는 class여야 한다고 생각했어요. 
  - 그리고 프로그램 전반에서 ContactManager가 단 1개의 instance만 있으면 될 것이라 생각해서 singleton으로 구현했어요. 
- 그런데 최근, 싱글톤을 택하기 보다 이를 지양하고 다른 대안을 택한다는 말을 얼핏 들은 기억이 있어요.
- 질문
  - 제가 싱글톤 패턴을 선택한 이유에 대한 vivi의 의견은 어떠한지와 다른 괜찮은 대안이 있는지 궁금합니다!

2022-12-27 07:29 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +typealias InfoInput = (name: String, age: String, phone: String)
- 유저에게 받는 input의 format은 name, age, phone으로 고정되어 있고, 각 type을 검증하기 위해 만든 UserInfo도 마찬가지로 name, age, phone 타입으로 고정되어 있습니다. 
- 각각 반환 타입과 매개변수 타입으로 중복이 되는 동시에 유저의 입력이 갖는 의미가 name, age, phone임을 나타낼 수 있기에 typealias로 작성 후 tuple에 name, age, phone 이라는 하면 더 가독성 좋은 코드가 될 것 같았어요.

2022-12-27 07:31 UTC, SunnnySong commented on .gitignore
> +.DS_Store
branch를 파고 merge를 하는 과정에서 .DS_Store 파일이 다시 들어간 듯 합니다!
.DS_Store 삭제 완료했습니다~

2022-12-27 07:38 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/Error.swift
> +    public var errorDescription: String? {
- 이유
  - Naming과 Error 처리를 고민하면서 참고했던 코드 중 하나가 Alamofire의 [AFError.swift](https://github.com/Alamofire/Alamofire/blob/master/Source/AFError.swift) 였어요! 그러면서 LocalizedError 프로토콜을 알게 되었고 그에 관한 [글](https://ios-development.tistory.com/849)도 찾아봤어요!
  - 해당 파일과 글에서 errorDescription을 정의하는 방식을 참고했어요.
  ```swift
  extension SomeError: LocalizedError {
    public var errorDescription: String? {
      // ..
    }
  }
  ```
- 의견
  - 그런데 vivi의 질문을 보고 곰곰히 생각해보니 AFError가 public인 이유는 Alamofire가 open source library이기 때문인 것 같고,
  - ContactManager project 내에서만 쓸 IOError의 경우 public이 붙을 이유가 없이, default인 internal access로도 충분하다고 판단 후 public을 지웠습니다!
  - 날카로운 질문 감사해요!
- 질문
  - 제가 제대로 생각 및 판단한게 맞는지 궁금해요🤔

2022-12-27 07:41 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +        입력 형태를 확인해주세요.
- 의견
  - 처음에 help를 StringLiteral에 넣은 이유는 모든 String 상수들을 StringLiteral이라는 파일 안에 넣고 사용하고자 계획했기 때문입니다.
  - 처음에 help를 계획한 이유는, "입력 형식을 확인하려면 help를 타이핑해주세요." 라는 안내 문구를 error 설명 뒤에 붙이고, 사용자가 `help`를 입력할 경우 올바른 입력 형식 예시를 출력하려 했습니다. 하지만 시간 관계상 step1에서는 이를 생략하였고, 추후 구현할 예정이었어요.
  - 그런데 만약 지금처럼 그냥 "입력 형태를 확인해주세요." 만 있다면, 그리고 그것을 에러 설명 뒤에만 붙인다면, Error의 static let property로 만들어도 괜찮을 것 같습니다.
- 질문
  - 일반적인 컨벤션은 위의 경우 "입력 형식을 ~ 타이핑 해주세요." 라는 안내를 어디에 구현하는지 궁금해요!
  - 이 프로젝트에 지금 help를 어떻게 하는게 좋을까요...?🤔

2022-12-27 07:44 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/UserInfo.swift
> +enum UserInfoParams {
eter를 치기 귀찮았던 저를 반성합니다ㅎㅎ😆
명확하고 가독성 좋은 코드를 작성하기 위해 축약하던 기존의 나쁜 버릇을 고쳐야겠어요!

2022-12-27 07:46 UTC, SunnnySong commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        }
"/", " / " 를 검증하기 위한 방법으로 contains와 components가 아닌  더 효율적인 방법을 구현하다가 정규식을 사용하기로 결정했습니다!
 
```swift
let inputPattern = #"^.+\b(?<sep>( \/ )|(\/))(\b[^\s]+\b)\k<sep>(\b[^\s]+)$"#
```

extension으로 String을 정규식으로 체크하는 함수를 생성하고, 사용자 입력을 이 함수를 사용해 inputPattern 정규식으로 검증했습니다.

2022-12-27 07:47 UTC, SunnnySong commented on ios-contact-manager/ios-contact-manager/Error.swift
> +}
discord로 질문하여 코드에 반영했습니다~ 늦은 시간에 답변 주셔서 감사합니당!

2022-12-27 07:47 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/UserInfo.swift
> +            return "^[A-Za-z ]+$"
네! 프로젝트의 요구사항 중
```text
이름은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다
```
를 반영하기 위해 띄어쓰기가 있는 이름도 유효한 이름으로 판단 후 띄어쓰기를 제거해주었어요.

2022-12-27 07:50 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/Error.swift
> +}
좋은 지적 감사합니다! vivi의 둘 다 생각에 동의해서 Error의 네이밍과 구조를 수정했어요😆

2022-12-27 07:54 UTC, vanism2091 commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        return (splited[0], splited[1], splited[2])
vivi의 제안을 고려해 아래와 같이 수정했어요!
```swift
// ContactManager.swift
private func parse(_ input: String) throws -> InfoInput {
    // ..
    return (name: splitedInput[0], age: splitedInput[1], phone: splitedInput[2])
}
```
이렇게 수정하는 것이 바람직한 방향 맞나요?

2022-12-27 07:54 UTC, SunnnySong commented on ios-contact-manager/ios-contact-manager/Extension.swift
> +    func getInfoAfter(type: UserInfoParams) throws -> String {
기존 getInfoAfter(type: ) 에서 matches(infoType: )으로 변경하였습니다. 
해당 함수가 String을 infoType 별 정규식으로 검증하는 함수이기 때문에, matches(in:options:range:) method를 참고해 작명하였습니다.

2022-12-27 07:56 UTC, SunnnySong commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +enum StringLiteral {
- 의견 :
프로젝트 안에서 사용할 문구들을 모두 모아 놓은 namespace를 만들고 싶어서 StringLiteral 타입을 생성했습니다! 인스턴스 생성을 막기 위해 enum타입으로 만들고, static으로 각 문구를 저장했습니다. 
구현을 할 때, 저희는 String extension으로 구현할 방법을 생각해내지 못해서 StringLiteral 타입으로 생성했었습니다. 
- 질문:
vivi의 리뷰를 받고 String extension에 대해 생각을 해보았는데, 그럼 문구가 쓰이는 파일마다 fileprivate extension String 으로 문구를 extension하는 방법으로 접근하는게 맞을까요?

2022-12-27 14:54 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +typealias InfoInput = (name: String, age: String, phone: String)
설명 감사해요! 😄
`InfoInput`과 `UserInfo`를 나눠서 작성하신 것과 같이 더 가독성을 좋게 작성하기 위한 의도를 이해했어요 👍👍

2022-12-27 14:55 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +    static let shared = ContactManager()
프로그램 전반에서 `ContactManager`가 하나만 존재할 거라는 맥락을 이해했어요~!!
저와 같은 생각으로 싱글톤 패턴을 사용하신 거 같아요 ㅎㅎ 설명 고맙습니다 😆

2022-12-27 14:58 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/ContactManager.swift
> +        return (splited[0], splited[1], splited[2])
이전보다 가독성이 좋아졌다고 생각해요!

사실 저는 return 구문이 길어지는 것 보다 깔끔하게 변수 하나를 반환하는 게 깔끔해 보인다고 생각하는데,
`typealias` 로 `InfoInput` 를 정의하고 있을 때는 현재와 같은 방식도 가독성이 나쁘지 않은 거 같아요 😊

2022-12-27 14:58 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/Error.swift
> +    public var errorDescription: String? {
`ContactManager project 내에서만 쓸 IOError의 경우 public이 붙을 이유가 없이, default인 internal access로도 충분하다고 판단 후 public을 지웠습니다!` 에 대해 공감했습니다!
상세한 의견 나눠줘서 고마워요 이즈, 써니 🙌👍

2022-12-27 15:03 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +enum StringLiteral {
프로젝트 안에서 사용할 문구들을 모아 놓기 위한 용도로 `StringLiteral` 타입을 생성하셨군요! 👀
`String` extension 을 사용한다면 질문해주신 것과 같이 fileprivate extension 으로 사용할 수도 있겠지만, 그럼 프로젝트를 수행하는 로직과 문구 타입이 항상 같은 파일에 위치해야 한다는 점(이런 파일이 많아진다면 특정 문구를 찾기 쉽지 않을 수 있다는 점..!!)을 고려해본 후 결정하는 게 좋을 거 같아요 😄

또한, 문자열만 관리하고자 한다면 Xcode에서는 `.strings` 파일을 활용하기도 한다는 점 참고로 말씀드려요~!! (추후 사용할 일이 있을 거에요)

2022-12-27 15:04 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/UserInfo.swift
> +    case name, phone
`한 줄로 나열해도 가독성이 좋아서 한 줄로 나열`한 이유에 공감했어요~
일관성 보다는 읽히기 쉬운 지금과 같은 형태도 괜찮다고 생각합니다!

2022-12-27 15:07 UTC, YebinKim commented on ios-contact-manager/ios-contact-manager/StringLiteral.swift
> +        입력 형태를 확인해주세요.
StringLiteral 을 구현하신 의도를 이해했어요!
또한, 추후 구현을 위해 이름을 help로 설정하셨다면 이 부분은 필수로 수정하지 않아도 괜찮을 거 같습니다 ☺️

Xcode에서 Strings 를 관리하는 방법 중 하나는 이 [코멘트](https://github.com/tasty-code/ios-contact-manager/pull/5#discussion_r1057731107)에서 함께 공유 드렸으니 참고 부탁드려요~

2022-12-27 15:11 UTC, YebinKim approved these changes
써니, 이즈 안녕하세요~
수정해주신 부분들 확인했습니다! 꼼꼼한 코멘트 확인 감사드려요 😆👍

제가 추가로 코멘트 달아둔 부분은 코멘트 Resolve 처리를 시켜두지 않았는데,
이후 코멘트를 확인하신 후 확인에 대한 표시를 알려주시기 위해 코멘트를 Resolve 처리 부탁드려요 🙏 (만약 Resolve가 잘 수행되지 않는다면 알려주세요 😊)

이번 스텝에서의 핵심 경험은 충분히 충족되었다고 생각해 이대로 머지 진행할게요~!!
다음 스텝 진행도 화이팅입니다!! 🔥🥰

2022-12-27 15:11 UTC, merged