연락처관리 [STEP 1] Avery, Logan
tasty-code/ios-contact-manager pull request #6
Opened 2022-12-23 07:58 UTC by sloDevz

# 안녕하세요 Team AL 입니다.🥕🙌🏻

> 콘 안녕하세요 이번 연락처 프로그램을 함께 진행한 Avery와 Logan 입니다. :)
페어프로그래밍이 처음이라 많이 힘들었지만 일단 할 수 있는데 까지는 최선을 다해서 진행해 보았습니다.
예쁘게 봐주시고 좋은 피드백 부탁드리겠 습니다. 귀한시간 내주셔서 정말 감사합니다!
메리크리스마스 ~~ ⭐️🎄🎅🏻

# STEP 1 요구사항 : 사용자 입력 수신 및 검증
- 사용자의 입력을 받는 동작을 구현합니다.
    - Xcode에서 발생하는 한글 자소분리 현상은 과제 수행 중 해결해야 하는 문제가 아닙니다.
    - 사용자 이름 입력은 한글이 아닌, 영어로만 진행해주세요.
- **출력 내용과 입력방법은 예시와 똑같이 따릅니다.**
- 입력받은 문자열을 검증합니다
    - 올바른 사용자 입력 형태 : `[이름] / [나이] / [연락처]` / `[이름]/[나이]/[연락처]`
        - **이름**은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다
        - **나이**는 숫자로만 입력해야하며, **세 자리수 이하여야 합니다.**
        - **연락처**는 중간에 `-` 로 구분하며, `-` 는 두 개 존재해야합니다.
            - `-` 을 제외하고 숫자는 9자리 이상이어야 합니다.

# 구현 사항
- 유저의 입력데이터를 가공 처리
   - 유저가 입력한 데이터에 누락된게 없는지 확인
   - 입력 받은 데이터가 유효한 데이터인지 확인
   - name 데이터를 공백없이 가공
   - age 데이터가 유효한 형식으로 입력 됐는지 확인

# 모델링 의도
- 모든 연락처 정보를 담게 될 딕셔너리의 벨류값을 Person 구조체로 형성되도록 했습니다.

# 질문
- 딕셔너리를 이용해서 key가 이름, value가 나이와 번호로 설정하려고 했는데 이 방법에 대한 의견이 궁금합니다.
- 함수 이름과 변수이 어떻게 바뀌었으면 좋겠는지에 대한 피드백을 주셨으면 좋겠습니다.
- 최대한 함수들을 분할시켜 봤습니다. 너무 오버했거나 병합했으면 좋았을 함수들이 보인다면 피드백 부탁드립니다.
- 저희의 PR은 어떤지 궁금합니다. 

# 실행 예시

<img width="448" alt="Screen Shot 2022-12-23 at 4 27 14 PM" src="https://user-images.githubusercontent.com/29590768/209291769-5290426b-dba5-4d5c-9ac6-c95b3e1c2d23.png">

2022-12-25 09:30 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 질문에 대한 부분은 코멘트로 남겨놓았어요. 

개인적으로 저는 함수는 나눌 수 있다면 최대한 나누는게 좋지 않나 라는 생각을 갖고 있어요. 한 줄 짜리 코드라도 보다 더 의미있는 네이밍을 제공할 수 있다면 저는 함수로 분리하곤 해요. 또한 함수 분리보다 좋은 것이 객체로 분리하는 것이라고 생각해요.

두 분이 올려주신 PR에 요구사항도 함께 첨부해주셔서 리뷰하는데 편했어요! 또한 `.DS_Store`나 `xcworkspacedata` 같이 불필요한 파일은 다음 프로젝트에선 `.gitignore` 파일에 포함시켜주시면 좋을 것 같아요. `.gitignore`에 대해서도 한번 가볍게 살펴보시면 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/Literals/Message.swift
> +struct Message {
구조체로 구현한 이유가 궁금해요~ enum을 사용한다면 `private init() { }`도 제거할 수 있을 것 같아요!

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/Literals/Message.swift
> +    static let noUserInput = "아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요."
에러는 별도로 Error를 상속받는 사용자 정의 Error 타입으로 정의하고 메시지는 그 안에서 별도로 정의하는게 좋을 것 같아요

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/Model/Person.swift
> +    }
이건 수정사항이라기보단 그냥 팁(?) 정도 코멘트인데요! 구조체를 정의할 때 생성자를 별도로 정의하지 않아도 기본으로 모든 프로퍼티를 채울 수 있는 생성자를 제공해요!

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +class MyContactManager {
1. `MyContactManager`는 다른 객체에 의해 상속될 수 있나요~? 그렇지 않으면 `final`을 붙여 상속이 되지 않도록 해주는게 좋을 것 같아요. `final`을 붙이는 이유에 대해선 가볍게 학습해보시는걸 권장드려요. 다만 깊이 들어갈 수록 매우 어려운 주제일 수 있으니 현재는 가볍게만 읽어보시는게 좋을 것 같아요. 

2. `main.swift` 파일에 모두 넣지 말고 `MyContactManager`는 별도 디렉토리에 별도 파일로 분리하는게 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    private(set) var runValue: Bool = true
밑에 사용처를 보아하니 외부에서 이 변수를 보고 실행을 끝낼지 계속할지 판단하는 것 같은데, 외부 객체에서 내부 객체의 상태를 알고 있는건 좋지 않은 것 같아요. `MyContactManager` 객체 안에서 자체적으로 판단할 수 있도록 하는게 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +        let input = inputData.split(separator: "/").map { String($0) }
이 두 코드는 파싱된 결과를 반환하는 별도 메서드로 추출이 가능해보여요!

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +        }
이 부분도 파싱된 문자열을 분석해서 결과를 반환하는 메서드로 분리하면 좋을 것 같네요. 메서드는 결과만 반환하고 이를 어떻게 보여줄지 (콘솔에 출력을 하던, 화면에 보여주던)는 외부에서 판단하면 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +        getUserInput()
`getUserInput`도 더 나눠볼 수 있을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    private var personDictionary = [String : Person]()
현재 프로젝트 요구사항대로라면 별도로 `personDictionary`라는 곳에 연락처를 저장할 필요는 없어보이네요!

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
```swift 
private enum Constants {
  static let maximumAge = 999
  static let minimumAge = 1
}

private func validate(age rawValue: String) -> Bool { 
  guard let age = Int(rawValue) else { return false }
  return age <= Constants.maximumAge & age >= Constants.minimumAge
}
```

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
외부에서 문자열을 나누어서 넣어주는 것이 아니라 이 안에서 문자열을 받아 `Person?` 객체를 반환해주는건 어떨까요? 만약에 입력값이 하나 더 늘게 된다면 코드 수정이 필요한 곳이 많을 것 같아요. 

위에서 언급한 코멘트와 비슷하게, 현재 단계에서 저장하는 것이 프로젝트 요구사항은 아닌 것 같아요. 또한 저장한다해도, Person 객체를 어디다가 어떻게 저장할지는 외부에서 결정하는게 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
마찬가지로 직접 출력보단 출력에 용이한 형태로 가공된 문자열을 반환해주는 메서드가 되는게 좋을 것 같아요.

2022-12-25 09:30 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
검증과 출력을 모두 이 메서드에서 담당하고 있는데, 이를 분리해내면 좋을 것 같아요. 또한 에러를 던지지 않고, Bool을 반환하기로 결정한 이유도 궁금해요!

2022-12-27 02:00 UTC, sloDevz commented on MyContactManager/MyContactManager/Literals/Message.swift
> +struct Message {
Struct로 구성한 뒤에 private init()으로 생성자를 막으면 데이터의 낭비를 막을 수 있다고 생각했었는데 콘 덕분에 Enum의 용도에 대해서 새롭게 깨달은 바가 있었습니다
Enum은 항시 선택지를 한정짓기 위해서만 사용된다고 생각했는데 그게 아니라는걸 깨달았습니다 :)

2022-12-27 02:02 UTC, devxsby commented on MyContactManager/MyContactManager/Literals/Message.swift
> +    static let noUserInput = "아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요."
넵 !! 에러 타입은 따로 LocalizedError 프로토콜을 채택한 Errors 열거형으로 만들어서 따로 확인하도록 수정하였습니다 !!
이런 방식으로 개선하는게 맞을까요 ??! 🤔

```swift
enum Errors: String, LocalizedError {
    case wrongAge = "입력한 나이정보가 잘못되었습니다. 입력 형식을 확인해주세요."
    case wrongPhoneNumber = "입력한 연락처정보가 잘못되었습니다. 입력 형식을 확인해주세요."
    case defaultError = "입력한 정보가 잘못되었습니다. 입력 형식을 확인해주세요."
    case noUserInput = "아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요."
    
    var errorDescription: String? {
        return self.rawValue
    }
}

```

2022-12-27 02:03 UTC, sloDevz commented on MyContactManager/MyContactManager/Model/Person.swift
> +    }
감사합니다..! 😆

2022-12-27 02:14 UTC, devxsby commented on MyContactManager/MyContactManager/main.swift
> +class MyContactManager {
처음에 `final` 키워드를 적으려고 했지만 아직 해당 내용에 대해 개념적 확신이 없어서 넣지 않았어요 .. !!
콘님이 언급해주신 덕분에 이번에 다시 제대로 공부하고 넘어가야 할 필요성을 느꼈어요 감사해요!! 👍🏻

1. 제가 `final` 이해한 내용을 간단히 정리하자면 아래와 같아요 !! 혹시 맞는지 확인해주실 수 있으실까요~?

> Swift 에서는 다른 언어와 비슷하게 클래스를 상속해 서브클래스를 구현할 수 있는데 만약, 해당 클래스가 더이상 상속이 필요없거나 특정 속성은 오버라이드하지 않아야 한다면 `final` 키워드를 붙이는 것이 좋다 👀
 
> final 키워드를 통해 더 이상 상속이 필요없음을 명시할 수 있고, 오버라이드 할 시 컴파일 에러를 발생시킬 수 있다.
 명시적으로 상속되지 않는 것 외에 런타임 성능이 향상된다는 장점도 있기 때문에 장점이 많다 ..! → Swift Performance 증가!


2. 일단은 `main.swift`에서 `MyContactManager`를 분리했어요. 그런데 `MyContactManager `도 객체로 더욱 잘게 나눌 수 있을 것 같은데 어떻게 하면 좋을까요..!?? 객체로 나눌때 보통 어떠한 기준으로 나누시는지 궁금해요 🙌🏻
3.

2022-12-27 02:20 UTC, devxsby commented on MyContactManager/MyContactManager/main.swift
> +        let input = inputData.split(separator: "/").map { String($0) }
좋은 의견 감사합니다 !! `getUserInput ` 메서드로 분리하는 방식으로 변경해보았어요 ~!

```swift
    let userInput = getUserInput()
```

```swift
    private func trimming(of str:String) -> [String] {
        let unspacedString = str.components(separatedBy: " ").joined()
        let splitedString = unspacedString.split(separator: "/").map { String($0) }
        return splitedString
    }
    
    private func getUserInput() -> [String]? {
        guard let userInput = readLine() else { return nil }
        return trimming(of: userInput)
    }
```

2022-12-27 02:24 UTC, sloDevz commented on MyContactManager/MyContactManager/main.swift
> +    private(set) var runValue: Bool = true
- 말씀하신대로 `runValue` 를 직접적으로 노출하지 않도록 수정해봤어요!
- `MyContactManager`의 `runProgram()` 안으로 while문을  옮기고 `main()`에서는 `MyContactManager`의 내부 사정은 더이상 알 수 없고 오로지 실행 메서드만 호출 할 수 있도록 했어요.⭐️
- 뿐만 아니라 `MyContactManager`내부적으로도 `runValue`를 직접 컨택하지 않고 `isProgramRun()`과 `terminateProgram()`으로 해당 값을 확인 및 변경하는 매서드를 따로 두어 조금 더 보안이 강화된(?) 코드를 작성해 보았어요 (제대로 한건지는 잘 모르겠지만요😉)
- 처음엔 왜 이게 바람직하지 않는지 이해가 잘 안됐지만 막상 해놓고보니 `MyContactManager`인스턴스의 독립성이 더욱 뚜렷해지는걸 느꼈어요 아마도 이걸 바라신 거인지는 잘 모르겠지만 객채지향적 프로그래밍을 조금더 이해하는 순간이었어요 👍🏻

```swift
    func runProgram() {
        while isProgramRun() {
            ...
            }
        }
    }
.
.
.
.
    private func isProgramRun() -> Bool {
        return runValue
    }
    
    private func terminateProgram() {
        runValue = false
    }

```

2022-12-27 02:24 UTC, devxsby commented on MyContactManager/MyContactManager/main.swift
> +    private var personDictionary = [String : Person]()
뒤에 스탭을 고려해서 설계해보았는데 안좋은 습관인 것 같아요..! 😿
다음 스탭은 해당 요구사항위주로 구현하도록 할게요 감사해요 !

2022-12-27 02:33 UTC, sloDevz commented on MyContactManager/MyContactManager/main.swift
> +        }
해당 코드는 저희가 Do Catch 에러처리를 하게됨으로 많은 수정을 했어요. 😆
- `checkValid()`가 입력된 불확실한 문자열을 받아서 해당 문자열에 문제가 없다면 유효한 문자열로 반환해주는 역할을 하도록 했어요👍🏻
- `checkValid()` 안에는 나이 데이터를 유효한 값으로 체크 및 변환해주는`getValidAge()`와 전화번호의 유효성을 체크하고 반환해주는 `getValidNumber()`가 각각의 역할을 또 따로 분담받아서 작동하도록 했어요.👯

2022-12-27 02:43 UTC, sloDevz commented on MyContactManager/MyContactManager/main.swift
> +    }
고민을 많이 해봤는데도 이 부분은 제대로 이해가 되지 않았어요...ㅠㅠ 🤦🏻‍♂️
그래도 일단은 콘의 의견을 최대한 고민하고 이해해서 코드를 수정해보긴 했어요.. (하지만 확신이 없어요😅)

이해하기 힘들었던 점을 정리해보자면
- "출력에 용이한" 이란 말을 이해하기가 어려웠어요
- 출력에 용이한 형태라는게 어떤걸 의미하는건가요?
- 제 생각엔 저 `printResult`안에는 각각의 요소만 입력되면 출력이 되도록 작성을 한건데 결국 저 파라미터들이 "출력이 용이하게 가공된" 데이터들이지 않을까 생각했어요
- 이미 출력에 용이하도록 가공된 데이터를 받아서 처리하는 메서드에서 다시 출력이 용이하게 반환해야 한다 라고 느껴져서 혼란이 왔었어요..😭
- 사실 제대로 된 예시를 보지를 못해서 제가 계속 깨닫지 못하는거 같아서 괜찮은 예시가 있다면 보여주시길 부탁드려요 ..🥹

2022-12-27 02:45 UTC, devxsby commented on MyContactManager/MyContactManager/main.swift
> +    }
객체지향적인 접근이 아직 어렵네요.. ! 😢 열심히 공부중이에요 !!
일단은 `person` 객체만 반환해주는 메서드를 만들어서 객체만 따로 관리하라는 말씀 맞으실까요?
다음 STEP2에 반영해서 해보도록 할게요 !! 👌🏻

2022-12-27 02:48 UTC, devxsby commented on MyContactManager/MyContactManager/main.swift
> +    }
저희가 아직 에러처리에 관한 방법을 익히지 못해서 이번에 적용해보도록 해봤어요.
`do-catch 구문` 적용해서 에러 처리한 바뀐 코드로 다시 한 번 봐주실 수 있으실까요~~?

2022-12-27 05:04 UTC, protocorn93 commented on MyContactManager/MyContactManager/Literals/Message.swift
> +    static let noUserInput = "아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요."
```swift 
enum ContactAppError: LocalizedError {
    case wrongAge
    case wrongPhoneNumber
    case defaultError
    case noUserInput
    
    var errorDescription: String? {
      switch self { 
        case .wrongAge: 
          return "blah blah"
        ...
      }
    }
}
```

에러의 경우 서버 응답 코드와 rawValue를 매칭해서 사용하곤해요. 그래서 rawValue에 출력 문구를 사용하는건 지양하는게 좋아요. `LocalizedError` 채택을 통한 `errorDescription`를 사용하기도 하고 그냥 간단히 `errorMessage`와 같이 사용자 정의 프로퍼티를 사용하기도해요~

2022-12-27 05:08 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +class MyContactManager {
1. 네네 현재 이해하신 정도로도 충분한 것 같아요~! 나중에 Swift Performance 관련 WWDC 영상도 찾아보시면 좋을 것 같아요. 이에 대한 내용도 자세히 어렵게 나오거든요! 
2. 음! 요건 정석대로 이야기하자면 하나의 객체는 하나의 역할만 하도록 설계한다고들 해요! 이걸 객체로 빼야겠다라는 생각을 언제하냐면 "이게 하나의 역할이 될 수 있겠는데?" 라고 스스로 생각이 들더라구요. (지극히 주관적이네요 🤯) 이 프로젝트를 예를 들어 Validation은 별도 객체로 뺄 수 있겠는데? 입니다! 또한 객체안의 특정 프로퍼티를 특정 메서드만 사용하고 있다면 해당 프로퍼티와 해당 메서드를 별도 객체로 분리해보려 시도도 하는 것 같아요!

2022-12-27 05:32 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
조금 장황해질 수 있지만 코멘트를 남기자면

현재 MyContactManager는 입력/검증/가공/출력을 모두 담당하고 있어요. 그리고 `printResult` 메서드는 이중 출력을 담당하고 있죠. 하지만 맥락을 모두 알고 있어야 해요. "`name`, `age`, `number`를 받아서 콘솔창에 출력을 한다" 

만약에 사는 곳, 직장, 닉네임이 추가되고, 이름이 아니라 성/이름으로 분리되고 또한 콘솔창이 아닌 화면에 보여주어야 한다는 요구사항으로 바뀌면 어떻게 될까요? 다시 단순 화면에 보여주는게 아니라 알럿 창에 보여주어야 한다고 다시 바뀌면 어떻게 될까요?

인자가 바뀌니 호출부도 수정이 필요하겠죠. 문구가 변경되거나 사용자에게 보여주어야 하는 방법도 달라지니 당연히 메서드의 내용도 바뀔거에요.  요구사항 변경에 따라 코드 이곳저곳에 수정사항이 생겨요.

여기서 우리가 요구사항을 조금 추상화해보면 "입력한 정보(`Person`객체)를 사용자에게 보여주자" 정도가 될 것 같아요. 저라면 

```swift 
func makeSuccessMessage(person: Person) -> String { 
  return " ... "
}
```

이런 메서드(혹은 Presenter 객체)를 만들어 사용할 것 같아요. 이 메서드의 내용이 변경될 이유는 한 가지에요. 문구가 변경되었을 때죠. 우리가 객체지향을 공부할 때 단일 책임 원칙을 말을 하는데, 여기서 객체는 한 가지 일을 한다는 정의도 있지만, 변경될 이유가 한 가지여야 한다는 의미도 존재해요.

2022-12-27 05:36 UTC, protocorn93 commented on MyContactManager/MyContactManager/main.swift
> +    }
네네~ 잘 보았습니다! 👍

추가로 한 가지만 더 말씀드리고 싶은 것은, 수정 사항도 수정 사항 하나당 하나의 커밋으로 작성해주시면 좋을 것 같아요. 그리고 PR 커뮤니케이션을 할 때는 

> [1d32002](https://github.com/tasty-code/ios-contact-manager/pull/6/commits/1d32002594b3ae0b06ff2326821850e5c8310650) 여기에 이렇게 수정했어요!

라고 해주시면 리뷰어가 리뷰를 하기에도 보다 수월해요! 요건 현업에서도 이렇게 진행하고 있어요!

2022-12-27 07:45 UTC, merged