ContactManager [Step 1] Toughie, iyeah
tasty-code/ios-contact-manager pull request #8
Opened 2022-12-26 07:27 UTC by Toughie17

@SungPyo

**웨더 안녕하세요, Toughie & iyeah 입니다 🙂**  
iyeah가 이틀 늦게 합류하게 되어 원래 PR 시기보다 조금 늦어졌음을 양해 부탁드립니다..!</br>
페어프로그래밍이 처음이지만 주어진 시간 안에 최선을 다해 작성해 보았습니다.</br>
시간 내어 봐주셔서 감사하고 피드백 부탁드리겠습니다. 월요일 파이팅하세요!</br>

## **프로젝트 수행시 제약사항**
- 코드에 느낌표(!)를 사용하지 않습니다.</br>
- Swift API Design Guidelines 의 문서대로 코드를 작성합니다.</br>
- 들여쓰기는 3번을 초과하지 않습니다.</br>
- 한 커밋의 코드 단위에 대해 고민하여 진행합니다.</br>

## **1단계 구현 요구사항 - 사용자 입력 수신 및 검증**
- 입력받은 내용을 검증하여 사용자에게 안내문을 출력합니다.  
- 사용자의 입력을 받는 동작을 구현합니다.  
- 한글 자소분리 현상은 과제 수행 중 해결해야 하는 문제가 아닙니다.  
- 사용자 이름 입력은 한글이 아닌, 영어로만 진행해주세요.  

- 올바른 사용자 입력 형태 : [이름] / [나이] / [연락처] / [이름]/[나이]/[연락처]  
- 이름: 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다.  
- 나이: 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.  
- 연락처: 중간에 - 로 구분하며, - 는 두 개 존재해야합니다. - 를 제외하고 숫자는 9자리 이상이어야 합니다.  

### **올바른 사용자 입력 예시** ###  
- james / 30 / 05-343-2334  
- ja mes / 30 / 013-3343-2343  
- james/30/013-3432-3433  
- 올바르지 않은 사용자 입력 예시  
- james / 서른 / 05-343-2334  
- ja mes / 30 / 01333432343  
- james/30세/013 3432 3433  
- james/013-3423-4432/30  

## **작업 목록** ##
- 사용자 입력 받기  
- 사용자 입력 검증  
- 실패 시: 에러 메세지 출력  
- 성공 시: 사용자 입력 정보 출력 
- (+입력받은 데이터를 Array에 저장)

## **학습 키워드**
- 올바르게 네이밍 하기 - [Swift API Design Guidelines] Naming 파트  
- guard 문 사용을 통한 Early-Exit  
- struct, enum의 활용  
- 정규표현식 검증  
- 조건문(if) 활용  

## **질문, 고민사항** ##  
- 변수명, 함수명 등 이름 짓기가 어려웠습니다. 더 직관적이고 좋은 네이밍이 있다면 알려주세요!  
- 함수 하나에 많은 함수들이 들어있던 구조에서 개별로 분해하는 작업을 거쳤습니다. 이를 통해 전역변수가 많아졌는데요, 이를 줄일 수 있는 방법이 있을까요?  
- 발견하지 못한 에러케이스가 있을까요?  
- 추가적으로 개선이 필요한 사항들이 있다면 많이 많이 알려주세요 :)

2022-12-26 11:28 UTC, SungPyo commented
Toughie, iyeah 안녕하세요. 처음뵙겠습니다.

첫 리뷰네요 잘 부탁드립니다.

어떤 방식으로 리뷰가 진행되는지는 DM으로 나름 자세하게 전달을 드리겠습니다.

궁금한 부분은 언제든지 물어봐주시고 프로젝트 기간동안 잘 부탁드립니다.

질문에 대한 부분은 코멘트로 달아놨습니다 :)

---
> @SungPyo
> 
> **웨더 안녕하세요, Toughie & iyeah 입니다 🙂** iyeah가 이틀 늦게 합류하게 되어 원래 PR 시기보다 조금 늦어졌음을 양해 부탁드립니다..! 페어프로그래밍이 처음이지만 주어진 시간 안에 최선을 다해 작성해 보았습니다. 시간 내어 봐주셔서 감사하고 피드백 부탁드리겠습니다. 월요일 파이팅하세요!
> 
> ## **프로젝트 수행시 제약사항**
> * 코드에 느낌표(!)를 사용하지 않습니다.
> * Swift API Design Guidelines 의 문서대로 코드를 작성합니다.
> * 들여쓰기는 3번을 초과하지 않습니다.
> * 한 커밋의 코드 단위에 대해 고민하여 진행합니다.
> 
> ## **1단계 구현 요구사항 - 사용자 입력 수신 및 검증**
> * 입력받은 내용을 검증하여 사용자에게 안내문을 출력합니다.
> * 사용자의 입력을 받는 동작을 구현합니다.
> * 한글 자소분리 현상은 과제 수행 중 해결해야 하는 문제가 아닙니다.
> * 사용자 이름 입력은 한글이 아닌, 영어로만 진행해주세요.
> * 올바른 사용자 입력 형태 : [이름] / [나이] / [연락처] / [이름]/[나이]/[연락처]
> * 이름: 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다.
> * 나이: 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.
> * 연락처: 중간에 - 로 구분하며, - 는 두 개 존재해야합니다. - 를 제외하고 숫자는 9자리 이상이어야 합니다.
> 
> ### **올바른 사용자 입력 예시**
> * james / 30 / 05-343-2334
> * ja mes / 30 / 013-3343-2343
> * james/30/013-3432-3433
> * 올바르지 않은 사용자 입력 예시
> * james / 서른 / 05-343-2334
> * ja mes / 30 / 01333432343
> * james/30세/013 3432 3433
> * james/013-3423-4432/30
> 
> ## **작업 목록**
> * 사용자 입력 받기
> * 사용자 입력 검증
> * 실패 시: 에러 메세지 출력
> * 성공 시: 사용자 입력 정보 출력
> * (+입력받은 데이터를 Array에 저장)
> 
> ## **학습 키워드**
> * 올바르게 네이밍 하기 - [Swift API Design Guidelines] Naming 파트
> * guard 문 사용을 통한 Early-Exit
> * struct, enum의 활용
> * 정규표현식 검증
> * 조건문(if) 활용
> 
> ## **질문, 고민사항**
> * 변수명, 함수명 등 이름 짓기가 어려웠습니다. 더 직관적이고 좋은 네이밍이 있다면 알려주세요!
ㄴ `개발을 하다보면 이름짓기가 개발보다 어렵다는 우스갯 소리를 좀 볼 수 있는데요 저는 개인적으로 어느정도는 사실이라고 생각합니다 ㅎ; 저도 이름짓기를 굉장히 어려워 하긴 하는데 아직까진 괜찮은 것 같아요.`
> * 함수 하나에 많은 함수들이 들어있던 구조에서 개별로 분해하는 작업을 거쳤습니다. 이를 통해 전역변수가 많아졌는데요, 이를 줄일 수 있는 방법이 있을까요?
ㄴ `전역 변수가 필요한 경우도 있습니다. 아직 괜찮아요. 현재 상황에서는 전역변수를 줄이는것 보다 버그 없이, 크래시 없이, 가독성 좋게 프로그램을 실행하는게 최 우선이라고 생각됩니다.`
> * 발견하지 못한 에러케이스가 있을까요?
ㄴ `transform 함수 내부 실행에서 transformedInput 가 채워지지 않는다면 (입력이 올바르지 않다면) verifyInput 함수 실행시 앱이 종료될 수 있습니다. 이런 부분에 대한 에러케이스 개선이 더 우선인것 같아요.`
> * 추가적으로 개선이 필요한 사항들이 있다면 많이 많이 알려주세요 :)
ㄴ `가장 기초적이고 가장 기본적인것부터 하나씩 쳐 나가면 될 것 같아요. 우선 위 질문에 대한 답변을 참고해서 앱이 종료되는 상황부터 개선하면 좋을 것 같습니다!`

이 외에 수정하면 좋을 부분들 코드 코멘트로 달아두겠습니다.

수정 부탁드릴게요! :)

2022-12-26 11:30 UTC, SungPyo commented on ios_contact_manager/ios_contact_manager/main.swift
> +}
Enum도 타입입니다. Swift에서 타입의 첫글자는 대문자(파스칼케이스) 를 사용합니다.

2022-12-26 11:31 UTC, SungPyo commented on ios_contact_manager/ios_contact_manager/main.swift
> +verifyInput(input: transformedInput)
transform 함수에서 transformedInput 가 올바르게 완성되지 않는경우 (입력값: asdf) 
verifyInput 함수 실행시 앱이 종료될 위험이 있습니다.

2022-12-26 11:33 UTC, SungPyo commented on ios_contact_manager/ios_contact_manager/main.swift
> +verifyInput(input: transformedInput)
배열의 인덱스값을 안전하게 조회할 수 있는 방법을 한번 생각해봅시다!

2022-12-26 11:34 UTC, SungPyo requested changes
코드 수정후 다시 요청 부탁드립니다 :)

2022-12-27 02:24 UTC, iYeahh commented on ios_contact_manager/ios_contact_manager/main.swift
> +}
Enum 타입명 변경  
regularExpressionChecker -> RegularExpressionChecker (파라미터들도 함께 변경)

2022-12-27 02:27 UTC, iYeahh commented on ios_contact_manager/ios_contact_manager/main.swift
> +verifyInput(input: transformedInput)
transform 함수의 Guard else 구문에 return 처리가 되어있어 
transformdeInput의 값이 비어있을 경우에도(ex.이름,나이만 입력하는 경우)  
verifyInput 함수가 실행됨 -> 런타임 에러 발생 
  
이를 위해 verifyInput의 요소가 3개인지 확인하는 if문을 추가하였습니다.
-> subscript 문법을 통한 배열접근도 안전해졌다고 생각합니다.
(요소의 개수가 3개인 것을 확인하고 아래 코드들을 실행하기 때문에)  
  
 혹시 에러처리 구문인 do / catch 문 구현을 말씀하셨던 걸까요?

2022-12-27 07:53 UTC, SungPyo commented on ios_contact_manager/ios_contact_manager/main.swift
> +verifyInput(input: transformedInput)
do / catch 문 구현을 해도 상관없지만 그정도까지 생각했던건 아니었습니다.
if문 추가로 해결이 되긴 했지만 transform 함수 내에 있는 구문에서 verifyInput 를 호출해도 되지 않았을까 하는 생각이 들긴 하네요!

2022-12-27 07:53 UTC, SungPyo commented on ios_contact_manager/ios_contact_manager/main.swift
> +}
👍

2022-12-27 07:56 UTC, SungPyo approved these changes
수정사항 잘 확인했습니다.

다음 STEP 진행한번 해볼까요?

2022-12-27 07:57 UTC, merged