연락처관리 [STEP 1] Miro, Lust3r
tasty-code/ios-contact-manager pull request #9
Opened 2022-12-26 08:42 UTC by llimental

🙇🏼‍♂️ 인사말
========
안녕하세요 라자냐(@wonhee009)! Miro와 Lust3r 입니다.
STEP 1 요구 사항에 맞추어 코드를 작성하고 커밋을 해보았습니다.
둘 다 짝 프로그래밍이 처음이고 합을 맞추어 깃으로 작업하는 것이 아직은 어색하여 부족한 점이 많겠지만
많은 것을 배울 수 있던 시간이라고 생각합니다!

PR에 필요하다고 여겨지는 내용 작성하여 리뷰 요청드립니다. 감사합니다

✅ 요구사항 & 체크리스트
========
- [ ] 사용자의 입력을 받는 동작 구현
  - [ ] 이름 입력은 영어로 진행
- [ ] 출력 내용과 입력 방법은 예시와 똑같이 따름
- [ ] 입력받은 문자열 검증
  - [ ] 이름은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거
  - [ ] 나이는 숫자로만 입력해야하며, 세 자리수 이하여야 함
  - [ ] 연락처는 중간에 "-"로 구분하며, "-"는 두 개 존재해야 함
  - [ ] "-"를 제외하고 숫자는 9자리 이상이어야 함
- [ ] 입력받은 내용을 검증하여 사용자에게 안내문을 출력

📝 Summary
========
> 전체 입력값의 포맷 / 이름 / 나이 / 전화번호 입력값의 에러가 없으면 isError 변수 값을 통하여 while문에서 나올 수 있도록 하는 반복문을 통해 로직을 구현하였습니다.

🔎 구현 방법
========
## 전체 입력값의 포맷
```swift
if let input = readLine() {
        if !(calculateSlashNum(input: input)) {
            print("입력된 정보가 [이름]/[나이]/[전화번호] 형식인지 확인해주세요")
            continue
        }
        
        let add = input.components(separatedBy:"/")
        
        let trimName = add[0].trimmingCharacters(in: [" "])
        let trimAge = add[1].trimmingCharacters(in: [" "])
        let trimNum = add[2].trimmingCharacters(in: [" "])
        
        let zeroBlankName = trimName.components(separatedBy: [" "]).joined()
```
- readLine() 으로 받아들이는 것은 문자의 연속이기 때문에 input은 String으로 했습니다.
- add는 슬래시를 기준으로 input값을 나누어 각 항목으로 저장하기 때문에 Array<String>으로 했습니다.
- trimName, trimAge, trimNum은 add의 각 String을 받을 상수이기에 String으로 했습니다.

## 이름 입력값 검증
```swift
let regex = "^[A-Za-z\\s]+$"

func checkNameError(name: String) -> Bool{
    if name.range(of: regex, options: .regularExpression) == nil {
        print("이름이 잘못되었습니다.")
        print(name)
        return false
    }else {
        return true
    }
}
```
- input된 이름값이 정규식으로 지정한 영문이 맞는지 확인
> input값이 nil이 아닌 경우 true를, 정규식 검증을 통과하지 못할 경우 에러메세지 출력 및 false를 반환하는 함수 checkNameError 생성

## 나이 입력값 검증
```swift
func checkAgeError(age: String) -> Bool{
    if !age.allSatisfy({ $0.isNumber}){
        print("입력한 나이정보가 잘못되었습니다. 입력 형식을 확인해주세요.")
        return false
    } else if let changeToInt = Int(age) {
        if changeToInt >= 1000 {
            print("입력한 나이정보가 잘못되었습니다. 입력 형식을 확인해주세요.")
            print("숫자는 세자리수 이하로 입력해주세요.")
            return false
        }
    }
    return true
}
```
- input된 나잇값이 전체가 숫자인 지 확인
- input된 나잇값을 int로 변경 후 세자리 수 이하인 지 확인
> 최종적으로 위 두 검증을 통과할 경우 true를 , 통과하지 못할 경우 false를 던지는 함수인 checkAgeError를 생성

## 전화번호 입력값 검증
```swift
func calculateHyphenNum(input: String) -> Bool {
    if (input.filter { $0 == "-" }.count != 2) {
        return false
    }
    return true
}

func checkPhoneNumError(num: String) -> Bool {
    if !calculateHyphenNum(input: num){
        print("입력한 연락처정보가 잘못되었습니다. 입력 형식을 확인해주세요.")
        return false
    } else if num.components(separatedBy: ["-"]).joined().count < 9 {
        print("입력한 연락처정보가 잘못되었습니다. 입력 형식을 확인해주세요.")
        print("숫자는 9자리 이상이어야 합니다.")
        return false
    } else {
        return true
    }
}
```
> calculateHyphenNum 함수를 통해 입력받은 전화번호 값이 "-"을 2개 갖고 있는지 확인

- calculateHyphenNum을 통해 1차적으로 검증을 진행
- 검증된 값을 "-"으로 나누고, 그 값을 합친 후 개수가 9개보다 적은지 확인
- 적다면 에러 메세지 출력 후 false 반환, "-" 형식과 전화번호 개수가 9자리 이상이라면 true 반환

## 반복
```swift
var isError: Bool = true

while isError {
    print("")
    print("연락처 정보를 입력해주세요: ", terminator: "")
    
    if let input = readLine() {
        if !(calculateSlashNum(input: input)) {
            print("입력된 정보가 [이름]/[나이]/[전화번호] 형식인지 확인해주세요")
            continue
        }
        
        let add = input.components(separatedBy:"/")
        
        let trimName = add[0].trimmingCharacters(in: [" "])
        let trimAge = add[1].trimmingCharacters(in: [" "])
        let trimNum = add[2].trimmingCharacters(in: [" "])
        
        let zeroBlankName = trimName.components(separatedBy: [" "]).joined()
        
        if errorCheck(trimName: trimName, trimAge: trimAge, trimNum: trimNum){
            isError = false
            print("입력한 정보는 \(trimAge)세 \(zeroBlankName)(\(trimNum))입니다.")
        } else{
            continue
        }
    }
}
```
- 전체를 while문으로 감싸고 변수 isError 사용
- isError가 true인 상황에서 계속 입력값을 받을 수 있게 하였고, 전체 검증 함수인 errorCheck가 true를 반환한다면 isError를 false로 바꾸어 반복 종료
- errorCheck가 false를 반환한다면 continue로 while문 계속 진행

## 함수
> while문 내부에서 조건을 걸기보다 외부에 함수로 빼둔 후, 본 코드에서 불러오는 식으로 진행하는 것이 보기에 좋을 것 같아 진행했습니다.
그리고 전체 검증 함수인 errorCheck 안에서도 너무 많은 줄의 검증 코드가 있어 이름/나이/전화번호 검증 함수를 따로 뺀 후 errorCheck에서 실행하는 것으로 분리하였습니다.

🖥️ 실행결과
========
![image](https://user-images.githubusercontent.com/45708630/209525591-757121fd-5211-41ee-84de-b1c8ae3e743e.png)

🤔 궁금한 점
========
### 1. API Guideline을 참고하면서 함수 네이밍을 하였는데, 저희가 적절하게 함수 네이밍을 수행했는 지가 궁금합니다.
### 2. 저희가 while문 안에는 최소한 코드를 작성하기 위하여 세부적인 로직 구현은 함수로 다 빼내어서 코드를 작성하였는데, 이러한 방법의 코드 작성에 대한 리뷰어님의 의견이 궁금합니다.
### 3. 저희의 Commit 단위에 대한 리뷰어님의 피드백이 궁금합니다. 코드 한줄 한줄 추가한 거까지 commit을 하는 게 좋은 지 아니면 전체적인 로직을 추가할 때만 commit을 하는 게 좋은 지가 궁금합니다.
### 4. 저희 PR이 이렇게 작성하는 것이 맞는지 궁금합니다.
### 5. 구성을 크게 보면 단순하게 func와 while로 작성하였는데, 이걸 다른 구조체를 사용하여 구현한다면 어떤 것을 참조하는 것이 좋을지 궁금합니다.

2022-12-26 13:06 UTC, wonhee009 requested changes
수고하셨습니다 :)
코멘트 남겨두었으니 확인 부탁드려요.

2. 네 메서드로 로직들 분리한 부분 좋습니다.
3. 저도 최대한 커밋을 작게 나누는걸 좋아하는데요. 코드 한줄 한줄마다 커밋을 추가한다기 보다는 하나의 로직이 추가되었을때 커밋을 하는 편이긴 합니다.
4. 넵 좋습니다.
5. 구조체로 나눈다면 name, age, phoneNumber를 프로퍼티로 갖는 구조체로 분리할 순 있을거 같습니다.

2022-12-26 13:06 UTC, wonhee009 commented on contactManager/contactManager/main.swift
> +while isError {
`isError`라는 네이밍을 봤을때 `isError == true`일때가 에러상황일거 같은데요.
현재 로직에서는 반대되는 개념으로 사용하고 있는거 같습니다.
좀 더 헷갈리지 않을 네이밍으로 수정 부탁드립니다.

2022-12-27 00:41 UTC, longlivedrgn commented on README.md
> +
네! 필요없는 사항은 제거하겠습니다!

2022-12-27 00:41 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
> +    if let input = readLine() {
넵 알겠습니다! guard문 공부해서 바로 수정하겠습니다 감사합니다 :)

2022-12-27 00:41 UTC, llimental commented on contactManager/contactManager/main.swift
> +        print(name)
네 알겠습니다! 수정하도록 하겠습니다

2022-12-27 00:42 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
> +}
return 타입을 생각하지않고, 함수 naming을 한 것 같습니다. 수정하겠습니다!

2022-12-27 00:45 UTC, longlivedrgn commented on contactManager/contactManager/main.swift
> +        let add = input.components(separatedBy:"/")
입력 값을 하나의 array에 넣는다는 느낌으로 네이밍을 했는데, 다시 고민해보고 함수 naming 수정해보겠습니다!

2022-12-27 00:45 UTC, llimental commented on contactManager/contactManager/main.swift
> +    }
네 알겠습니다! guard 사용법 더 학습하여 적용해보도록 하겠습니다

2022-12-27 00:46 UTC, llimental commented on contactManager/contactManager/main.swift
> +while isError {
다른 리뷰해주신 항목들 반영하면서 isError 부분도 명확한 이름으로 변경하거나 사용을 달리해보도록 하겠습니다
상세한 코멘트 감사드립니다

2022-12-27 04:57 UTC, llimental commented
안녕하세요 라자냐(@wonhee009)
저희 PR 검토해주셔서 감사합니다!
코멘트 주신 내용을 반영하여 수정 커밋 진행해 보았습니다.

😎 변경사항
====
- calculateSlashNum 함수 네이밍 변경
> "/"가 입력규칙대로 2개가 들어왔는지 확인하는 기능이었기 때문에 입력값을 검증한다는 뜻으로 validateSlashInput 으로 변경하였습니다.

- add 상수 네이밍 변경
> 기존에는 입력 값을 하나의 array에 넣는다는 느낌으로 네이밍을 진행하였는데, "/" 기준으로 입력값이 나눠졌다는 의미로서 seperatedInput 으로 상수명을 변경하였습니다.

- 출력문 명세서와 동일하게 변경
> 명세서를 참고하여 변경하였습니다.

- isError 변수명 변경
> 기존의 변수명의 의미가 명확하지 않았기에, repeatLoop 으로 변수명을 변경하였습니다.

- if 문에서 guard 사용
> guard를 사용하기 위해 공부를 해보았고, 그 용법에 맞게 기존 if문을 수정해보았습니다. 실제로 guard문으로 변경해 보면서 기존 코드보다 짧아지거나 가독성이 높아지는 것을 체감하였습니다.

- 공백값 예외처리
> 문구를 수정하면서 공백 input 값에 대한 예외처리가 되지 않은 것을 발견하여 guard 조건문에 해당 예외처리를 추가하였습니다.


🤔 궁금한점
====
1. 코멘트 바탕으로 수정을 해보았는데 모든 if문을 전부 guard로 변경한 것에 있어서 궁금한 점이 있습니다.
1-1. 현재 코드에서 전체를 바꾼 선택이 맞는 방향인지
1-2. if문 대신 guard를 이야기 해주셨던게 가독성 외에 다른 이유가 있으셨는지

2. 코드 중간중간 출력문이 나오는데, 같은 오류 메세지를 공유하는 과정이 있어서 이걸 효율적으로 따로 뺄 수 있는 방법이 있을까요?
가령 찾아보니 CustomStringConvertible이라는 프로토콜이 있다고하는데 적용하면 좋을 것 같지만 반대로 너무 과하게 진행하는 것이 아닐까 싶었습니다.

2022-12-27 11:31 UTC, wonhee009 requested changes
- `validateInputBySlash`도 괜찮을거 같네요.
- 'repeatLoop`라는 네이밍도 좋지만 해당 로직을 생각해보면 error인지 아닌지에 따라 while문을 도는거잖아요? 따라서 error의 유무가 네이밍에 드러나면 좋을거 같습니다. Miro, Lust3r이 아닌 다른 개발자가 해당 변수명을 봤을때에는 루프를 도는 flag인건 알겠지만 정확한 의미는 로직을 따라가야만 알 수 있으니까요.
- guard문에 링크 걸어둔 공식문서 읽어보셨을까요? guard문과 early exit의 관계를 생각해보면 좋을거 같습니다. (`continue`, `return`과 같은 부분이 early exit과 관계 있습니다.)
- 오류 메시지가 "입력한 00가 잘못되었습니다. 입력 형식을 확인해주세요." 이런 형식이 반복되는거로 보이는데요. 공통으로 뺄 수 있는 방법은 많습니다. 말씀 주신대로 해당 프로토콜을 사용하는 방법도 있을거고요.
```swift
enum Errortype {
   case name
   ...
}

func errorOutput(with type: ErrorType) -> String {
   let errorText: String
   switch  type {
      case .name: errorText = "이름"
      ...
   }
   print("입력한 \(errorText)가 잘못되었습니다. 입력 형식을 확인해주세요.")
}
```
이런 방식도 있을 수 있구요.

2022-12-28 01:20 UTC, longlivedrgn commented
안녕하세요 라자냐(@wonhee009)
바쁜 와중에도 저희 코드 검토해주셔서 감사합니다.🙇

변경사항
=====
1. `validateSlashInput` 함수 이름을 `validateInputBySlash`로 변경하였습니다
> `validateInputBySlash`이 'slash에의해 구분되는 입력값'을 더 잘 표현하므로 말씀해주신대로 변경해보았습니다.

2. `repeatLoop` 변수 이름 `repeatErrorMessage`로 변경
```swift
var repeatErrorMessage: Bool = true
let regex = "^[A-Za-z\\s]+$"

while repeatErrorMessage {
    print("")
    print("연락처 정보를 입력해주세요: ", terminator: "")
    
    guard let input = readLine(), input != "" else {
        print("아무것도 입력되지 않았습니다. 입력 형식을 확인해주세요.")
        continue
    }

    guard validateInputBySlash(input: input) else {
        print("입력된 정보가 [이름]/[나이]/[전화번호] 형식인지 확인해주세요")
        continue
    }
    
    let seperatedInput = input.components(separatedBy:"/")
    
    let trimName = seperatedInput[0].trimmingCharacters(in: [" "])
    let trimAge = seperatedInput[1].trimmingCharacters(in: [" "])
    let trimNum = seperatedInput[2].trimmingCharacters(in: [" "])
    
    let zeroBlankName = trimName.components(separatedBy: [" "]).joined()
    
    guard errorCheck(trimName: trimName, trimAge: trimAge, trimNum: trimNum) else {
        continue
    }
    repeatErrorMessage = false
    print("입력한 정보는 \(trimAge)세 \(zeroBlankName)(\(trimNum))입니다.")

}
```
> 위의 코드와 같이 while문 안에서 `repeatErrorMessage`가 true일 경우(에러 메세지 반복이 참일 경우) 지속적으로 오류 메세지를 print하고, while문 마지막에서 에러가 없다면 `repeatErrorMessage`변수를 false로 변경하여(에러 메세지 반복 = 거짓) 최종적으로 받은 입력값을 print해주고 while문에서 나가게 된다는 의미로써 변수명을 `repeatErrorMessage`로 설정하였습니다.


그리고 추가로 알려주신 내용(guard문, 오류 메세지 반복) 잘 확인했습니다!  감사합니다!😄

2022-12-28 01:55 UTC, wonhee009 approved these changes
`while !isError`, `while !validate` 정도의 네이밍 생각했었는데요.
while문이 repeat의 의미를 갖고 있다고 생각합니다.
네이밍은 저도 아직도 어려운 부분인데요. 네이밍을 로직을 모르는 사람이 볼 때 네이밍만 보고도 어떤 역할일지 예상 할 수 있도록 정하는걸 최우선으로 생각하고 있습니다.
repeatErrorMessage만 봤을 때에는 에러와 관련한 출력만 할거 같은데 안에 로직은 그렇지 않으니 혼란스러울 수 있을거 같습니다.
이 부분은 이후 스템에서 좀 더 고민해주세요.

2022-12-28 01:55 UTC, merged